UPDATE Units
SET NumInfPerEra = 20
WHERE Class = 'UNITCLASS_GREAT_DIPLOMAT';

UPDATE Defines SET Value = 35 WHERE Name = 'FRIENDSHIP_THRESHOLD_FRIENDS';
UPDATE Defines SET Value = 70 WHERE Name = 'FRIENDSHIP_THRESHOLD_ALLIES';
UPDATE Defines SET Value = 10 WHERE Name = 'MINOR_FRIENDSHIP_ANCHOR_MOD_PROTECTED';
UPDATE Defines SET Value = 0.5 WHERE Name = 'MOD_BALANCE_CORE_MINIMUM_RANKING_PTP';
UPDATE Language_en_US SET Text = '[NEWLINE][COLOR_WARNING_TEXT][ICON_BULLET] Must be in the top 50% of the world in terms of Military Power. Yours is ranked at {1_Num}% of world Military Power.[ENDCOLOR]' WHERE Tag = 'TXT_KEY_POP_CSTATE_PLEDGE_NEED_MORE_MILITARY_TT';

INSERT INTO Language_en_US (Tag, Text)
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV', 'A Shift in Alliance'  UNION ALL
/* SELECT 'TXT_KEY_BUILDING_BUDAPEST', 'Pearl of Danube' UNION ALL
SELECT 'TXT_KEY_BUILDING_BUDAPEST_HELP', 'Free 1 [ICON_RES_HORSE] Horse. +10% [ICON_PRODUCTION] Production when building Mounted Units.' UNION ALL */
SELECT 'TXT_KEY_BUILDING_BYBLOS', 'Byblos Cedar' UNION ALL
SELECT 'TXT_KEY_BUILDING_BYBLOS_HELP', '+1 [ICON_FOOD] Food to Oases, Lakes, and Fishing Boats.' UNION ALL
SELECT 'TXT_KEY_BUILDING_CAPE_TOWN', 'Cape of Good Hope' UNION ALL
SELECT 'TXT_KEY_BUILDING_CAPE_TOWN_HELP', '+10% [ICON_INTERNATIONAL_TRADE] Trade Route Length. Finishing a [ICON_INTERNATIONAL_TRADE] Trade Route generates 20-40 [ICON_GOLD] Gold scaling on the Designated City''s [ICON_CITIZEN] Population.' UNION ALL
SELECT 'TXT_KEY_BUILD_MARSH', 'Create a Marsh'  UNION ALL
SELECT 'TXT_KEY_BUILD_MARSH_HELP', 'Terraforms the landscape here into the marsh while installing an improvement that''ll stabilize the marsh. The improvement will lose 1 [ICON_FOOD] Food when the alliance is not maintained. Requires an alliance with [COLOR_POSITIVE_TEXT]Brussels[ENDCOLOR].'  UNION ALL
SELECT 'TXT_KEY_BUILD_MOUND', 'Construct a Mound'  UNION ALL
SELECT 'TXT_KEY_BUILD_MOUND_HELP', 'When built adjacent to cities, the improvement gains +1 [ICON_GOLDEN_AGE] Golden Age Point. Adjacent Villages and Towns receive +1 [ICON_GOLD] Gold and [ICON_PEACE] Faith. Mounds lose certain bonuses when the alliance is not maintained. Requires an alliance with [COLOR_POSITIVE_TEXT]Cahokia[ENDCOLOR].' UNION ALL
SELECT 'TXT_KEY_IMPROVEMENT_MARSH', 'Marsh' UNION ALL
SELECT 'TXT_KEY_CIV5_IMPROVEMENTS_MARSH', 'To restore the marshlands on any terrain, just allow water to flow to it naturally. It should even work on snow! If the water doesn''t freeze that is.' UNION ALL
SELECT 'TXT_KEY_IMPROVEMENT_MARSH_HELP', 'Only with the alliance of the Brussel people can a civilization continue a restoration project of marshlands.' UNION ALL
SELECT 'TXT_KEY_IMPROVEMENT_MOUND', 'Mound' UNION ALL
SELECT 'TXT_KEY_CIV5_IMPROVEMENTS_MOUND', 'It is a pyramid built of transported soil and clay.' UNION ALL
SELECT 'TXT_KEY_IMPROVEMENT_MOUND_HELP', 'Only with the alliance of the Cahokia people can a civilization enjoy such a beauty of a structure.' UNION ALL
SELECT 'TXT_KEY_BUILDING_GENEVA', 'Ecclesiastical' UNION ALL
SELECT 'TXT_KEY_BUILDING_GENEVA_HELP', '+1 [ICON_PEACE] Faith for every 5 [ICON_CITIZEN] Citizens. Requires an alliance with [COLOR_POSITIVE_TEXT]Geneva[ENDCOLOR].' UNION ALL
SELECT 'TXT_KEY_BUILDING_HONG_KONG', 'Prosperous' UNION ALL
SELECT 'TXT_KEY_BUILDING_HONG_KONG_HELP', '+1 [ICON_GOLD] Gold for every 6 [ICON_CITIZEN] Citizens. Requires an alliance with [COLOR_POSITIVE_TEXT]Hong Kong[ENDCOLOR].' UNION ALL
SELECT 'TXT_KEY_BUILDING_JERUSALEM', 'Holy City' UNION ALL
SELECT 'TXT_KEY_BUILDING_JERUSALEM_HELP', 'This is the holy city. Too many have made the pilgrimage to this city for their religion.' UNION ALL
SELECT 'TXT_KEY_BUILDING_KABUL', 'Paradise on Earth' UNION ALL
SELECT 'TXT_KEY_BUILDING_KABUL_HELP', 'City gains +0.66 [ICON_CULTURE] Culture for every Mountain within 3 tiles of the City. Requires an alliance with [COLOR_POSITIVE_TEXT]Kabul[ENDCOLOR].' UNION ALL
SELECT 'TXT_KEY_BUILDING_KATHMANDU', 'The Mountain' UNION ALL
SELECT 'TXT_KEY_BUILDING_KATHMANDU_HELP', 'City gains +0.66 [ICON_PEACE] Faith for every Mountain within 3 tiles of the City. Requires an alliance with [COLOR_POSITIVE_TEXT]Kathmandu[ENDCOLOR].' UNION ALL
SELECT 'TXT_KEY_BUILDING_KIEV', 'Bylina' UNION ALL
SELECT 'TXT_KEY_BUILDING_KIEV_HELP', 'Provides a Musician Slot. Requires an alliance with [COLOR_POSITIVE_TEXT]Kiev[ENDCOLOR]. Can never be destroyed.' UNION ALL
SELECT 'TXT_KEY_BUILDING_LHASA', 'Potala Palace' UNION ALL
SELECT 'TXT_KEY_BUILDING_LHASA_HELP', '+1 and +10% [ICON_CULTURE] Culture and [ICON_FOOD] Food. Grants 1 additional delegate in the World Congress. Requires an alliance with [COLOR_POSITIVE_TEXT]Lhasa[ENDCOLOR] and an active session of the [COLOR_POSITIVE_TEXT]World Congress[ENDCOLOR]. Yield modifiers halved without the alliance. Can never be destroyed.' UNION ALL
SELECT 'TXT_KEY_BUILDING_LHASA_QUOTE', '[NEWLINE][TAB][TAB]"The first time I stepped onto the rooftop of the Potala Palace, I felt, as never before or since, as if I were stepping onto the rooftop of my being; onto some dimension of consciousness that I''d never visited before."[NEWLINE] – Pico Iyer' UNION ALL
SELECT 'TXT_KEY_BUILDING_MILAN', 'Visconti Emissary' UNION ALL
SELECT 'TXT_KEY_BUILDING_MILAN_HELP', 'Provides an Artist Slot. Requires an alliance with [COLOR_POSITIVE_TEXT]Milan[ENDCOLOR]. Can never be destroyed.' UNION ALL
SELECT 'TXT_KEY_BUILDING_RAGUSA', 'Maritime Suzeranity' UNION ALL
SELECT 'TXT_KEY_BUILDING_RAGUSA_HELP', 'City-State Alliances generate +1 [ICON_FOOD] Food. Requires an alliance with [COLOR_POSITIVE_TEXT]Ragusa[ENDCOLOR].' UNION ALL
SELECT 'TXT_KEY_BUILDING_RIGA', 'Latvian Commercialism' UNION ALL
SELECT 'TXT_KEY_BUILDING_RIGA_HELP', '+3% [ICON_FOOD] Food. Requires an alliance with [COLOR_POSITIVE_TEXT]Riga[ENDCOLOR].' UNION ALL
SELECT 'TXT_KEY_BUILDING_SAMARKAND', 'The Sogd' UNION ALL
SELECT 'TXT_KEY_BUILDING_SAMARKAND_HELP', '+4 [ICON_GOLD] Gold from Foreign Trade Routes to both origin and designated civilization.' UNION ALL
SELECT 'TXT_KEY_BUILDING_VALLETTA', 'The Grand Harbor' UNION ALL
SELECT 'TXT_KEY_BUILDING_VALLETTA_HELP', 'Requires an alliance with [COLOR_POSITIVE_TEXT]Valletta[ENDCOLOR]. City must have a Fishing Boat resource improved. Yield bonuses removed without the alliance. +15 XP for all Naval Units. Can never be destroyed.' UNION ALL
SELECT 'TXT_KEY_BUILDING_VILNIUS', 'The Gate of Dawn' UNION ALL
SELECT 'TXT_KEY_BUILDING_VILNIUS_HELP', 'Provides a Writer Slot. Requires an alliance with [COLOR_POSITIVE_TEXT]Vilnius[ENDCOLOR]. Can never be destroyed.';

INSERT INTO Policies (Type, Description)
SELECT 'POLICY_ALMATY', 'TXT_KEY_CITYSTATE_ALMATY'UNION ALL
SELECT 'POLICY_BOGOTA', 'TXT_KEY_CITYSTATE_BOGOTA' UNION ALL
SELECT 'POLICY_BUCHAREST', 'TXT_KEY_CITYSTATE_BUCHAREST' UNION ALL
SELECT 'POLICY_GENOA', 'TXT_KEY_CITYSTATE_GENOA' UNION ALL
SELECT 'POLICY_IFE', 'TXT_KEY_CITYSTATE_IFE' UNION ALL
SELECT 'POLICY_LHASA', 'TXT_KEY_CITYSTATE_LHASA' UNION ALL
SELECT 'POLICY_SOFIA', 'TXT_KEY_CITYSTATE_SOFIA' UNION ALL
SELECT 'POLICY_SYDNEY', 'TXT_KEY_CITYSTATE_SYDNEY' UNION ALL
SELECT 'POLICY_TYRE', 'TXT_KEY_CITYSTATE_TYRE' UNION ALL
SELECT 'POLICY_UR', 'TXT_KEY_CITYSTATE_UR' UNION ALL
SELECT 'POLICY_VATICAN_CITY', 'TXT_KEY_CITYSTATE_VATICAN_CITY';

UPDATE Policies
SET GreatGeneralExtraBonus = 5
WHERE Type = 'POLICY_SOFIA';

UPDATE Policies
SET FaithCostModifier = -10
WHERE Type = 'POLICY_VATICAN_CITY';

INSERT INTO Policy_YieldGPExpend (PolicyType, YieldType, Yield)
SELECT 'POLICY_GENOA', 'YIELD_GOLD', 50 UNION ALL
SELECT 'POLICY_GENOA', 'YIELD_GOLDEN_AGE_POINTS', 15 UNION ALL
SELECT 'POLICY_LHASA', 'YIELD_FAITH', 25;

INSERT INTO Policy_ConquerorYield (PolicyType, YieldType, Yield)
SELECT 'POLICY_BOGOTA', 'YIELD_CULTURE', 20;

INSERT INTO Policy_YieldChangeTradeRoute (PolicyType, YieldType, Yield)
SELECT 'POLICY_ALMATY', 'YIELD_SCIENCE', 1 UNION ALL
SELECT 'POLICY_UR', 'YIELD_FOOD', 2;

INSERT INTO Policy_YieldFromBorderGrowth (PolicyType, YieldType, Yield)
SELECT 'POLICY_IFE', 'YIELD_FAITH', 3;

INSERT INTO Policy_GreatWorkYieldChanges (PolicyType, YieldType, Yield)
SELECT 'POLICY_BUCHAREST', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'POLICY_TYRE', 'YIELD_GOLD', 2;

INSERT INTO Policy_WLTKDYieldMod (PolicyType, YieldType, Yield)
SELECT 'POLICY_SYDNEY', 'YIELD_FOOD', 5;

INSERT INTO UnitPromotions (Type, Description, Help, CannotBeChosen, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry)
SELECT 'PROMOTION_ANTANANARIVO', 'TXT_KEY_CITYSTATE_ANTANANARIVO', 'TXT_KEY_CSTRAIT_MINOR_CIV_ANTANANARIVO', 1, 'AS2D_IF_LEVELUP', 7, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CITYSTATE_ANTANANARIVO_HELP1' UNION ALL
SELECT 'PROMOTION_BELGRADE', 'TXT_KEY_CITYSTATE_BELGRADE', 'TXT_KEY_CSTRAIT_MINOR_CIV_BELGRADE', 1, 'AS2D_IF_LEVELUP', 8, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CITYSTATE_BELGRADE_HELP1' UNION ALL
SELECT 'PROMOTION_HANOI', 'TXT_KEY_CITYSTATE_HANOI', 'TXT_KEY_CSTRAIT_MINOR_CIV_HANOI', 1, 'AS2D_IF_LEVELUP', 9, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CITYSTATE_HANOI_HELP1' UNION ALL
SELECT 'PROMOTION_MBANZA_KONGO', 'TXT_KEY_CITYSTATE_MBANZA_KONGO', 'TXT_KEY_CSTRAIT_MINOR_CIV_MBANZA_KONGO', 1, 'AS2D_IF_LEVELUP', 11, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CITYSTATE_MBANZA_KONGO_HELP1' UNION ALL
SELECT 'PROMOTION_SIDON', 'TXT_KEY_CITYSTATE_SIDON', 'TXT_KEY_CSTRAIT_MINOR_CIV_SIDON', 1, 'AS2D_IF_LEVELUP', 13, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CITYSTATE_SIDON_HELP1' UNION ALL
SELECT 'PROMOTION_YEREVAN', 'TXT_KEY_CITYSTATE_YEREVAN', 'TXT_KEY_CSTRAIT_MINOR_CIV_YEREVAN', 1, 'AS2D_IF_LEVELUP', 14, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CITYSTATE_YEREVAN_HELP1';

UPDATE UnitPromotions
SET MaxHitPointsChange = 25
WHERE Type = 'PROMOTION_BELGRADE';

UPDATE UnitPromotions
SET FriendlyLandsModifier = 10
WHERE Type = 'PROMOTION_HANOI';

UPDATE UnitPromotions
SET EnemyHealChange = 5
WHERE Type = 'PROMOTION_SIDON';

INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT 'PROMOTION_ANTANANARIVO', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_ANTANANARIVO', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_ANTANANARIVO', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_ANTANANARIVO', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_ANTANANARIVO', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_ANTANANARIVO', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_ANTANANARIVO', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_ANTANANARIVO', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_ANTANANARIVO', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_ANTANANARIVO', 'UNITCOMBAT_NAVALRANGED' UNION ALL
SELECT 'PROMOTION_ANTANANARIVO', 'UNITCOMBAT_FIGHTER' UNION ALL
SELECT 'PROMOTION_ANTANANARIVO', 'UNITCOMBAT_BOMBER' UNION ALL
SELECT 'PROMOTION_BELGRADE', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_HANOI', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_HANOI', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_HANOI', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_HANOI', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_HANOI', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_HANOI', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_HANOI', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_HANOI', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_HANOI', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_HANOI', 'UNITCOMBAT_NAVALRANGED' UNION ALL
SELECT 'PROMOTION_MBANZA_KONGO', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_MBANZA_KONGO', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_MBANZA_KONGO', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_MBANZA_KONGO', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_MBANZA_KONGO', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_MBANZA_KONGO', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_MBANZA_KONGO', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_MBANZA_KONGO', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_SIDON', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_SIDON', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_SIDON', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_SIDON', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_SIDON', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_SIDON', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_SIDON', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_SIDON', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_SIDON', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_SIDON', 'UNITCOMBAT_NAVALRANGED' UNION ALL
SELECT 'PROMOTION_YEREVAN', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_YEREVAN', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_YEREVAN', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_YEREVAN', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_YEREVAN', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_YEREVAN', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_YEREVAN', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_YEREVAN', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_YEREVAN', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_YEREVAN', 'UNITCOMBAT_NAVALRANGED' UNION ALL
SELECT 'PROMOTION_YEREVAN', 'UNITCOMBAT_FIGHTER' UNION ALL
SELECT 'PROMOTION_YEREVAN', 'UNITCOMBAT_BOMBER';

INSERT INTO UnitPromotions_Features (PromotionType, FeatureType, DoubleMove, Attack, Defense)
SELECT 'PROMOTION_MBANZA_KONGO', 'FEATURE_FOREST', 0, 15, 15 UNION ALL
SELECT 'PROMOTION_MBANZA_KONGO', 'FEATURE_JUNGLE', 0, 15, 15 UNION ALL
SELECT 'PROMOTION_MBANZA_KONGO', 'FEATURE_MARSH', 0, 15, 15 UNION ALL
SELECT 'PROMOTION_MBANZA_KONGO', 'FEATURE_FLOOD_PLAINS', 0, 15, 15;

INSERT INTO UnitPromotions_YieldFromKills (PromotionType, YieldType, Yield)
SELECT 'PROMOTION_ANTANANARIVO', 'YIELD_GOLD', 100 UNION ALL
SELECT 'PROMOTION_YEREVAN', 'YIELD_CULTURE', 50;

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
/* SELECT 'BUILDINGCLASS_BUDAPEST', 'BUILDING_BUDAPEST', 'TXT_KEY_BUILDING_BUDAPEST' UNION ALL */
SELECT 'BUILDINGCLASS_BYBLOS', 'BUILDING_BYBLOS', 'TXT_KEY_BUILDING_BYBLOS' UNION ALL
SELECT 'BUILDINGCLASS_CAPE_TOWN', 'BUILDING_CAPE_TOWN', 'TXT_KEY_BUILDING_CAPE_TOWN' UNION ALL
SELECT 'BUILDINGCLASS_GENEVA', 'BUILDING_GENEVA', 'TXT_KEY_BUILDING_GENEVA' UNION ALL
SELECT 'BUILDINGCLASS_HONG_KONG', 'BUILDING_HONG_KONG', 'TXT_KEY_BUILDING_HONG_KONG' UNION ALL
SELECT 'BUILDINGCLASS_JERUSALEM', 'BUILDING_JERUSALEM', 'TXT_KEY_BUILDING_JERUSALEM' UNION ALL
SELECT 'BUILDINGCLASS_KABUL', 'BUILDING_KABUL', 'TXT_KEY_BUILDING_KABUL' UNION ALL
SELECT 'BUILDINGCLASS_KATHMANDU', 'BUILDING_KATHMANDU', 'TXT_KEY_BUILDING_KATHMANDU' UNION ALL
SELECT 'BUILDINGCLASS_KIEV', 'BUILDING_KIEV', 'TXT_KEY_BUILDING_KIEV' UNION ALL
SELECT 'BUILDINGCLASS_LHASA', 'BUILDING_LHASA', 'TXT_KEY_BUILDING_LHASA' UNION ALL
SELECT 'BUILDINGCLASS_MILAN', 'BUILDING_MILAN', 'TXT_KEY_BUILDING_MILAN' UNION ALL
SELECT 'BUILDINGCLASS_RAGUSA', 'BUILDING_RAGUSA', 'TXT_KEY_BUILDING_RAGUSA' UNION ALL
SELECT 'BUILDINGCLASS_RIGA', 'BUILDING_RIGA', 'TXT_KEY_BUILDING_RIGA' UNION ALL
SELECT 'BUILDINGCLASS_SAMARKAND', 'BUILDING_SAMARKAND', 'TXT_KEY_BUILDING_SAMARKAND' UNION ALL
SELECT 'BUILDINGCLASS_VALLETTA', 'BUILDING_VALLETTA', 'TXT_KEY_BUILDING_VALLETTA' UNION ALL
SELECT 'BUILDINGCLASS_VILNIUS', 'BUILDING_VILNIUS', 'TXT_KEY_BUILDING_VILNIUS';

UPDATE BuildingClasses
SET MaxGlobalInstances = 1
WHERE Type = 'BUILDINGCLASS_LHASA';

INSERT INTO Audio_Sounds (SoundID, Filename, LoadType)
SELECT 'SND_WONDER_LHASA', 'PotalaPalace', 'DynamicResident';

INSERT INTo Audio_2DSounds (ScriptID, SoundID, SoundType, MinVolume, MaxVolume, IsMusic, TaperSoundtrackVolume)
SELECT 'AS2D_WONDER_LHASA', 'SND_WONDER_LHASA', 'GAME_MUSIC_STINGS', 85, 85, 1, '0.0';

INSERT INTO Buildings (Type, BuildingClass, Cost, GoldMaintenance, PrereqTech, Description, Help, MinAreaSize, NukeImmune, ConquestProb, NeverCapture, HurryCostModifier, IconAtlas, PortraitIndex, IsDummy)
/* SELECT 'BUILDING_BUDAPEST', 'BUILDINGCLASS_BUDAPEST', -1, 0, NULL, 'TXT_KEY_BUILDING_BUDAPEST', 'TXT_KEY_BUILDING_BUDAPEST_HELP', -1, 1, 0, 1, 5, 'BW_ATLAS_1', 7, 1 UNION ALL */
SELECT 'BUILDING_BYBLOS', 'BUILDINGCLASS_BYBLOS', -1, 0, NULL, 'TXT_KEY_BUILDING_BYBLOS', 'TXT_KEY_BUILDING_BYBLOS_HELP', -1, 1, 0, 1, 5, 'BW_ATLAS_1', 58, 1 UNION ALL
SELECT 'BUILDING_CAPE_TOWN', 'BUILDINGCLASS_CAPE_TOWN', -1, 0, NULL, 'TXT_KEY_BUILDING_CAPE_TOWN', 'TXT_KEY_BUILDING_CAPE_TOWN_HELP', -1, 1, 0, 1, 5, 'BW_ATLAS_1', 26, 1 UNION ALL
SELECT 'BUILDING_GENEVA', 'BUILDINGCLASS_GENEVA', -1, 0, NULL, 'TXT_KEY_BUILDING_GENEVA', 'TXT_KEY_BUILDING_GENEVA_HELP', -1, 1, 0, 1, 5, 'BW_ATLAS_1', 37, 1 UNION ALL
SELECT 'BUILDING_HONG_KONG', 'BUILDINGCLASS_HONG_KONG', -1, 0, NULL, 'TXT_KEY_BUILDING_HONG_KONG', 'TXT_KEY_BUILDING_HONG_KONG_HELP', -1, 1, 0, 1, 5, 'BW_ATLAS_1', 50, 1 UNION ALL
SELECT 'BUILDING_JERUSALEM', 'BUILDINGCLASS_JERUSALEM', -1, 0, NULL, 'TXT_KEY_BUILDING_JERUSALEM', 'TXT_KEY_BUILDING_JERUSALEM_HELP', -1, 1, 100, 0, 5, 'UCS_ATLAS', 1, 1 UNION ALL
SELECT 'BUILDING_KABUL', 'BUILDINGCLASS_KABUL', -1, 0, NULL, 'TXT_KEY_BUILDING_KABUL', 'TXT_KEY_BUILDING_KABUL_HELP', -1, 1, 0, 1, 5, 'UCS_ATLAS', 1, 1 UNION ALL
SELECT 'BUILDING_KATHMANDU', 'BUILDINGCLASS_KATHMANDU', -1, 0, NULL, 'TXT_KEY_BUILDING_KATHMANDU', 'TXT_KEY_BUILDING_KATHMANDU_HELP', -1, 1, 0, 1, 5, 'UCS_ATLAS', 1, 1 UNION ALL
SELECT 'BUILDING_KIEV', 'BUILDINGCLASS_KIEV', 350, 2, NULL, 'TXT_KEY_BUILDING_KIEV', 'TXT_KEY_BUILDING_KIEV_HELP', -1, 1, 0, 1, 5, 'EXPANSION_BW_ATLAS_1', 3, 0 UNION ALL
SELECT 'BUILDING_LHASA', 'BUILDINGCLASS_LHASA', 650, 0, NULL, 'TXT_KEY_BUILDING_LHASA', 'TXT_KEY_BUILDING_LHASA_HELP', -1, 1, 100, 0, -5, 'UCS_ATLAS', 0, 0 UNION ALL
SELECT 'BUILDING_MILAN', 'BUILDINGCLASS_MILAN', 350, 2, NULL, 'TXT_KEY_BUILDING_MILAN', 'TXT_KEY_BUILDING_MILAN_HELP', -1, 1, 0, 1, 5, 'CITIZEN_ATLAS', 4, 0 UNION ALL
SELECT 'BUILDING_RAGUSA', 'BUILDINGCLASS_RAGUSA', -1, 0, NULL, 'TXT_KEY_BUILDING_RAGUSA', 'TXT_KEY_BUILDING_RAGUSA_HELP', -1, 1, 0, 1, 5, 'UCS_ATLAS', 1, 1 UNION ALL
SELECT 'BUILDING_RIGA', 'BUILDINGCLASS_RIGA', -1, 0, NULL, 'TXT_KEY_BUILDING_RIGA', 'TXT_KEY_BUILDING_RIGA_HELP', -1, 1, 0, 1, 5, 'UCS_ATLAS', 2, 1 UNION ALL
SELECT 'BUILDING_SAMARKAND', 'BUILDINGCLASS_SAMARKAND', -1, 0, NULL, 'TXT_KEY_BUILDING_SAMARKAND', 'TXT_KEY_BUILDING_SAMARKAND_HELP', -1, 1, 0, 1, 5, 'EXPANSION2_BUILDING_ATLAS', 8, 1 UNION ALL
SELECT 'BUILDING_VALLETTA', 'BUILDINGCLASS_VALLETTA', 250, 1, NULL, 'TXT_KEY_BUILDING_VALLETTA', 'TXT_KEY_BUILDING_VALLETTA_HELP', -1, 1, 0, 1, 5, 'BW_ATLAS_1', 26, 0 UNION ALL
SELECT 'BUILDING_VILNIUS', 'BUILDINGCLASS_VILNIUS', 350, 2, NULL, 'TXT_KEY_BUILDING_VILNIUS', 'TXT_KEY_BUILDING_VILNIUS_HELP', -1, 1, 0, 1, 5, 'UCS_ATLAS', 3, 0;

UPDATE Buildings
SET TradeRouteSeaDistanceModifier = 10, TradeRouteLandDistanceModifier = 10
WHERE Type = 'BUILDING_CAPE_TOWN';

UPDATE Buildings
SET ReligiousPressureModifier = 100, ConversionModifier = -50
WHERE Type = 'BUILDING_JERUSALEM';

UPDATE Buildings
SET SpecialistType = 'SPECIALIST_MUSICIAN', SpecialistCount = 1, EventChoiceRequiredActive = 'PLAYER_EVENT_CHOICE_MINOR_CIV_KIEV'
WHERE Type = 'BUILDING_KIEV';

UPDATE Buildings
SET SpecialistType = 'SPECIALIST_ARTIST', SpecialistCount = 1, EventChoiceRequiredActive = 'PLAYER_EVENT_CHOICE_MINOR_CIV_MILAN'
WHERE Type = 'BUILDING_MILAN';

UPDATE Buildings
SET WonderSplashImage = 'APotalaPalace.dds', WonderSplashAudio = 'AS2D_WONDER_LHASA', WonderSplashAnchor = 'L,B', PolicyType = 'POLICY_LHASA', Quote = 'TXT_KEY_BUILDING_LHASA_QUOTE', SingleLeagueVotes = 1
WHERE Type = 'BUILDING_LHASA';

UPDATE Buildings
SET TradeRouteTargetBonus = 4, TradeRouteRecipientBonus = 4
WHERE Type = 'BUILDING_SAMARKAND';

UPDATE Buildings
SET ExtraCityHitPoints = 25, Water = 1, EventChoiceRequiredActive = 'PLAYER_EVENT_CHOICE_MINOR_CIV_VALLETTA'
WHERE Type = 'BUILDING_VALLETTA';

UPDATE Buildings
SET SpecialistType = 'SPECIALIST_WRITER', SpecialistCount = 1, EventChoiceRequiredActive = 'PLAYER_EVENT_CHOICE_MINOR_CIV_VILNIUS'
WHERE Type = 'BUILDING_VILNIUS';

INSERT INTO Building_YieldPerXTerrainTimes100 (BuildingType, TerrainType, YieldType, Yield)
SELECT 'BUILDING_KABUL', 'TERRAIN_MOUNTAIN', 'YIELD_CULTURE', 66 UNION ALL
SELECT 'BUILDING_KATHMANDU', 'TERRAIN_MOUNTAIN', 'YIELD_FAITH', 66;

/* INSERT INTO Building_ResourceQuantity(BuildingType, ResourceType, Quantity)
SELECT 'BUILDING_BUDAPEST', 'RESOURCE_HORSE', 1; */

INSERT INTO Building_YieldPerAlly (BuildingType, YieldType, Yield)
SELECT 'BUILDING_RAGUSA', 'YIELD_FOOD', 1;

/* INSERT INTO Building_UnitCombatProductionModifiers(BuildingType, UnitCombatType, Modifier)
SELECT 'BUILDING_BUDAPEST', 'UNITCOMBAT_MOUNTED', 10; */

INSERT INTO Building_YieldChanges(BuildingType, YieldType, Yield)
SELECT 'BUILDING_LHASA', 'YIELD_FOOD', 1 UNION ALL
SELECT 'BUILDING_LHASA', 'YIELD_CULTURE', 1;

INSERT INTO Building_YieldChangesPerPop (BuildingType, YieldType, Yield)
SELECT 'BUILDING_GENEVA', 'YIELD_FAITH', 20 UNION ALL
SELECT 'BUILDING_HONG_KONG', 'YIELD_GOLD', 16;

INSERT INTO Building_LakePlotYieldChanges (BuildingType, YieldType, Yield)
SELECT 'BUILDING_BYBLOS', 'YIELD_FOOD', 1;

INSERT INTO Building_YieldModifiers (BuildingType, YieldType, Yield)
SELECT 'BUILDING_LHASA', 'YIELD_CULTURE', 5 UNION ALL
SELECT 'BUILDING_LHASA', 'YIELD_FOOD', 5 UNION ALL
SELECT 'BUILDING_RIGA', 'YIELD_FOOD', 3;

INSERT INTO Building_LocalResourceOrs (BuildingType, ResourceType)
SELECT 'BUILDING_VALLETTA', 'RESOURCE_FISH' UNION ALL
SELECT 'BUILDING_VALLETTA', 'RESOURCE_CORAL' UNION ALL 
SELECT 'BUILDING_VALLETTA', 'RESOURCE_CRAB' UNION ALL 
SELECT 'BUILDING_VALLETTA', 'RESOURCE_PEARLS' UNION ALL 
SELECT 'BUILDING_VALLETTA', 'RESOURCE_WHALE';

INSERT INTO Building_DomainFreeExperiences (BuildingType, DomainType, Experience)
SELECT 'BUILDING_VALLETTA', 'DOMAIN_SEA', 15;

INSERT INTO Building_Flavors (BuildingType, FlavorType, Flavor)
SELECT 'BUILDING_KIEV', 'FLAVOR_GREAT_PEOPLE', 3 UNION ALL
SELECT 'BUILDING_LHASA', 'FLAVOR_WONDER', 10 UNION ALL
SELECT 'BUILDING_MILAN', 'FLAVOR_GREAT_PEOPLE', 3 UNION ALL
SELECT 'BUILDING_VALLETTA', 'FLAVOR_NAVAL_GROWTH', 10 UNION ALL
SELECT 'BUILDING_VILNIUS', 'FLAVOR_GREAT_PEOPLE', 3;
		
INSERT INTO Events (Type, Description, Help, EventArt, RandomChance, NumChoices, IgnoresGlobalCooldown, EventCooldown)
SELECT  'PLAYER_EVENT_MINOR_CIV_ALMATY', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ALMATY', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_ANTANANARIVO', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ANTANANARIVO', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_ANTWERP', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ANTWERP', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_BELGRADE', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BELGRADE', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_BOGOTA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BOGOTA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_BRATISLAVA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BRATISLAVA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_BRUSSELS', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BRUSSELS', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_BUCHAREST', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BUCHAREST', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_BUDAPEST', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BUDAPEST', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_BUENOS_AIRES', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BUENOS_AIRES', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_BYBLOS', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BYBLOS', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_CAHOKIA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_CAHOKIA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_CAPE_TOWN', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_CAPE_TOWN', 'AllianceShift.dds', -1, 1, 1, 1  UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_COLOMBO', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_COLOMBO', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_FLORENCE', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_FLORENCE', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_GENEVA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_GENEVA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_GENOA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_GENOA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_HANOI', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_HANOI', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_HONG_KONG', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_HONG_KONG', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_IFE', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_IFE', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_JERUSALEM', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_JERUSALEM', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_KABUL', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_KABUL', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_KATHMANDU', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_KATHMANDU', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_KIEV', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_KIEV', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_KUALA_LUMPUR', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_KUALA_LUMPUR', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_KYZYL', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_KYZYL', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_LA_VENTA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_LA_VENTA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_LHASA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_LHASA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_MALACCA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MALACCA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_MANILA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MANILA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_MBANZA_KONGO', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MBANZA_KONGO', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_MELBOURNE', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MELBOURNE', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_MILAN', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MILAN', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_MOGADISHU', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MOGADISHU', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_MOMBASA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MOMBASA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_MONACO', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MONACO', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_ORMUS', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ORMUS', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_PANAMA_CITY', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_PANAMA_CITY', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_PRAGUE', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_PRAGUE', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_QUEBEC_CITY', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_QUEBEC_CITY', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_RAGUSA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_RAGUSA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_RIGA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_RIGA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_SAMARKAND', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_SAMARKAND', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_SIDON', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_SIDON', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_SINGAPORE', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_SINGAPORE', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_SOFIA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_SOFIA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_SYDNEY', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_SYDNEY', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_TYRE', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_TYRE', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_UR', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_UR', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_VALLETTA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_VALLETTA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_VANCOUVER', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_VANCOUVER', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_VATICAN_CITY', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_VATICAN_CITY', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_VILNIUS', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_VILNIUS', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_WELLINGTON', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_WELLINGTON', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_WITTENBERG', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_WITTENBERG', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_YEREVAN', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_YEREVAN', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_ZANZIBAR', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ZANZIBAR', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_ZURICH', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ZURICH', 'AllianceShift.dds', -1, 1, 1, 1;

INSERT INTO EventChoices (Type, Description, Help, EventDuration, Expires, EventPolicy, EventPromotion, EventBuildingClassGlobal)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ALMATY', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ALMATY', 3, 1, 'POLICY_ALMATY', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ANTANANARIVO', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ANTANANARIVO', 3, 1, NULL, 'PROMOTION_ANTANANARIVO', NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ANTWERP', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ANTWERP', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BELGRADE', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BELGRADE', 3, 1, NULL, 'PROMOTION_BELGRADE', NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BOGOTA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BOGOTA', 3, 1, 'POLICY_BOGOTA', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BRATISLAVA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BRATISLAVA', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BRUSSELS', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BRUSSELS', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUCHAREST', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BUCHAREST', 3, 1, 'POLICY_BUCHAREST', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUDAPEST', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BUDAPEST', 3, 1, NULL, NULL, NULL /*'BUILDINGCLASS_BUDAPEST'*/ UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUENOS_AIRES', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BUENOS_AIRES', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BYBLOS', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_BYBLOS', 3, 1, NULL, NULL, 'BUILDINGCLASS_BYBLOS' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_CAHOKIA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_CAHOKIA', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_CAPE_TOWN', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_CAPE_TOWN', 3, 1, NULL, NULL, 'BUILDINGCLASS_CAPE_TOWN' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_COLOMBO', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_COLOMBO', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_FLORENCE', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_FLORENCE', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_GENEVA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_GENEVA', 3, 1, NULL, NULL, 'BUILDINGCLASS_GENEVA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_GENOA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_GENOA', 3, 1, 'POLICY_GENOA', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_HANOI', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_HANOI', 3, 1, NULL, 'PROMOTION_HANOI', NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_HONG_KONG', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_HONG_KONG', 3, 1, NULL, NULL, 'BUILDINGCLASS_HONG_KONG' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_IFE', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_IFE', 3, 1, 'POLICY_IFE', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_JERUSALEM', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_JERUSALEM', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_KABUL', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_KABUL', 3, 1, NULL, NULL, 'BUILDINGCLASS_KABUL' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_KATHMANDU', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_KATHMANDU', 3, 1, NULL, NULL, 'BUILDINGCLASS_KATHMANDU' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_KIEV', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_KIEV', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_KUALA_LUMPUR', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_KUALA_LUMPUR', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_KYZYL', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_KYZYL', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LA_VENTA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_LA_VENTA', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LHASA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_LHASA', 3, 1, 'POLICY_LHASA', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MALACCA', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MANILA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MANILA', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MBANZA_KONGO', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MBANZA_KONGO', 3, 1, NULL, 'PROMOTION_MBANZA_KONGO', NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MELBOURNE', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MELBOURNE', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MILAN', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MILAN', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MOGADISHU', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MOGADISHU', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MOMBASA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MOMBASA', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MONACO', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MONACO', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ORMUS', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_PANAMA_CITY', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_PANAMA_CITY', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_PRAGUE', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_PRAGUE', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_QUEBEC_CITY', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_QUEBEC_CITY', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_RAGUSA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_RAGUSA', 3, 1, NULL, NULL, 'BUILDINGCLASS_RAGUSA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_RIGA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_RIGA', 3, 1, NULL, NULL, 'BUILDINGCLASS_RIGA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_SAMARKAND', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_SAMARKAND', 3, 1, NULL, NULL, 'BUILDINGCLASS_SAMARKAND' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_SIDON', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_SIDON', 3, 1, NULL, 'PROMOTION_SIDON', NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_SINGAPORE', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_SINGAPORE', 3, 1, NULL, 'PROMOTION_NOBILITY', NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_SOFIA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_SOFIA', 3, 1, 'POLICY_SOFIA', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_SYDNEY', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_SYDNEY', 3, 1, 'POLICY_SYDNEY', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_TYRE', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_TYRE', 3, 1, 'POLICY_TYRE', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_UR', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_UR', 3, 1, 'POLICY_UR', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VALLETTA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_VALLETTA', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VANCOUVER', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_VANCOUVER', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VATICAN_CITY', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_VATICAN_CITY', 3, 1, 'POLICY_VATICAN_CITY', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VILNIUS', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_VILNIUS', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_WELLINGTON', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_WELLINGTON', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_WITTENBERG', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_WITTENBERG', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YEREVAN', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_YEREVAN', 3, 1, NULL, 'PROMOTION_YEREVAN', NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ZANZIBAR', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZURICH', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ZURICH', 3, 1, NULL, NULL, NULL;

INSERT INTO Event_ParentEvents (EventChoiceType, EventType)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ALMATY', 'PLAYER_EVENT_MINOR_CIV_ALMATY' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ANTANANARIVO', 'PLAYER_EVENT_MINOR_CIV_ANTANANARIVO' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ANTWERP', 'PLAYER_EVENT_MINOR_CIV_ANTWERP' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BELGRADE', 'PLAYER_EVENT_MINOR_CIV_BELGRADE' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BOGOTA', 'PLAYER_EVENT_MINOR_CIV_BOGOTA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BRATISLAVA', 'PLAYER_EVENT_MINOR_CIV_BRATISLAVA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BRUSSELS', 'PLAYER_EVENT_MINOR_CIV_BRUSSELS' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUCHAREST', 'PLAYER_EVENT_MINOR_CIV_BUCHAREST' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUDAPEST', 'PLAYER_EVENT_MINOR_CIV_BUDAPEST' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUENOS_AIRES', 'PLAYER_EVENT_MINOR_CIV_BUENOS_AIRES' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BYBLOS', 'PLAYER_EVENT_MINOR_CIV_BYBLOS' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_CAHOKIA', 'PLAYER_EVENT_MINOR_CIV_CAHOKIA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_CAPE_TOWN', 'PLAYER_EVENT_MINOR_CIV_CAPE_TOWN' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_COLOMBO', 'PLAYER_EVENT_MINOR_CIV_COLOMBO' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_FLORENCE', 'PLAYER_EVENT_MINOR_CIV_FLORENCE' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_GENEVA', 'PLAYER_EVENT_MINOR_CIV_GENEVA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_GENOA', 'PLAYER_EVENT_MINOR_CIV_GENOA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_HANOI', 'PLAYER_EVENT_MINOR_CIV_HANOI' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_HONG_KONG', 'PLAYER_EVENT_MINOR_CIV_HONG_KONG' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_IFE', 'PLAYER_EVENT_MINOR_CIV_IFE' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_JERUSALEM', 'PLAYER_EVENT_MINOR_CIV_JERUSALEM' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_KABUL', 'PLAYER_EVENT_MINOR_CIV_KABUL' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_KATHMANDU', 'PLAYER_EVENT_MINOR_CIV_KATHMANDU' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_KIEV', 'PLAYER_EVENT_MINOR_CIV_KIEV' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_KUALA_LUMPUR', 'PLAYER_EVENT_MINOR_CIV_KUALA_LUMPUR' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_KYZYL', 'PLAYER_EVENT_MINOR_CIV_KYZYL' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LA_VENTA', 'PLAYER_EVENT_MINOR_CIV_LA_VENTA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LHASA', 'PLAYER_EVENT_MINOR_CIV_LHASA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'PLAYER_EVENT_MINOR_CIV_MALACCA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MANILA', 'PLAYER_EVENT_MINOR_CIV_MANILA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MBANZA_KONGO', 'PLAYER_EVENT_MINOR_CIV_MBANZA_KONGO' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MELBOURNE', 'PLAYER_EVENT_MINOR_CIV_MELBOURNE' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MILAN', 'PLAYER_EVENT_MINOR_CIV_MILAN' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MOGADISHU', 'PLAYER_EVENT_MINOR_CIV_MOGADISHU' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MOMBASA', 'PLAYER_EVENT_MINOR_CIV_MOMBASA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MONACO', 'PLAYER_EVENT_MINOR_CIV_MONACO' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'PLAYER_EVENT_MINOR_CIV_ORMUS' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_PANAMA_CITY', 'PLAYER_EVENT_MINOR_CIV_PANAMA_CITY' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_PRAGUE', 'PLAYER_EVENT_MINOR_CIV_PRAGUE' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_QUEBEC_CITY', 'PLAYER_EVENT_MINOR_CIV_QUEBEC_CITY' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_RAGUSA', 'PLAYER_EVENT_MINOR_CIV_RAGUSA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_RIGA', 'PLAYER_EVENT_MINOR_CIV_RIGA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_SAMARKAND', 'PLAYER_EVENT_MINOR_CIV_SAMARKAND' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_SIDON', 'PLAYER_EVENT_MINOR_CIV_SIDON' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_SINGAPORE', 'PLAYER_EVENT_MINOR_CIV_SINGAPORE' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_SOFIA', 'PLAYER_EVENT_MINOR_CIV_SOFIA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_SYDNEY', 'PLAYER_EVENT_MINOR_CIV_SYDNEY' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_TYRE', 'PLAYER_EVENT_MINOR_CIV_TYRE' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_UR', 'PLAYER_EVENT_MINOR_CIV_UR' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VALLETTA', 'PLAYER_EVENT_MINOR_CIV_VALLETTA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VANCOUVER', 'PLAYER_EVENT_MINOR_CIV_VANCOUVER' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VATICAN_CITY', 'PLAYER_EVENT_MINOR_CIV_VATICAN_CITY' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VILNIUS', 'PLAYER_EVENT_MINOR_CIV_VILNIUS' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_WELLINGTON', 'PLAYER_EVENT_MINOR_CIV_WELLINGTON' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_WITTENBERG', 'PLAYER_EVENT_MINOR_CIV_WITTENBERG' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YEREVAN', 'PLAYER_EVENT_MINOR_CIV_YEREVAN' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'PLAYER_EVENT_MINOR_CIV_ZANZIBAR' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZURICH', 'PLAYER_EVENT_MINOR_CIV_ZURICH';

INSERT INTO EventChoice_ResourceQuantity (EventChoiceType, ResourceType, Quantity)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUDAPEST', 'RESOURCE_HORSE', 5;

INSERT INTO EventChoice_BuildingClassYieldChange (EventChoiceType, BuildingClassType, YieldType, YieldChange)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VALLETTA', 'BUILDINGCLASS_VALLETTA', 'YIELD_FOOD', 2 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VALLETTA', 'BUILDINGCLASS_VALLETTA', 'YIELD_SCIENCE', 2;

INSERT INTO EventChoice_BuildingClassYieldModifier (EventChoiceType, BuildingClassType, YieldType, Modifier)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_KUALA_LUMPUR', 'BUILDINGCLASS_WELL', 'YIELD_CULTURE', 5 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LHASA', 'BUILDINGCLASS_LHASA', 'YIELD_FOOD', 5 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LHASA', 'BUILDINGCLASS_LHASA', 'YIELD_CULTURE', 5;

INSERT INTO EventChoice_SpecialistYieldChange (EventChoiceType, SpecialistType, YieldType, YieldChange)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ANTWERP', 'SPECIALIST_MERCHANT', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_FLORENCE', 'SPECIALIST_ARTIST', 'YIELD_GOLDEN_AGE_POINTS', 2 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_WITTENBERG', 'SPECIALIST_CITIZEN', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_WITTENBERG', 'SPECIALIST_CIVIL_SERVANT', 'YIELD_FAITH', 1;

INSERT INTO EventChoice_BuildingClassYieldChange (EventChoiceType, BuildingClassType, YieldType, YieldChange)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BRATISLAVA', 'BUILDINGCLASS_WRITERS_GUILD', 'YIELD_CULTURE', 2 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BRATISLAVA', 'BUILDINGCLASS_ARTISTS_GUILD', 'YIELD_CULTURE', 2 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BRATISLAVA', 'BUILDINGCLASS_MUSICIANS_GUILD', 'YIELD_CULTURE', 2 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BRATISLAVA', 'BUILDINGCLASS_WRITERS_GUILD', 'YIELD_TOURISM', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BRATISLAVA', 'BUILDINGCLASS_ARTISTS_GUILD', 'YIELD_TOURISM', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BRATISLAVA', 'BUILDINGCLASS_MUSICIANS_GUILD', 'YIELD_TOURISM', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_IFE', 'BUILDINGCLASS_SHRINE', 'YIELD_CULTURE_LOCAL', 2 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_KUALA_LUMPUR', 'BUILDINGCLASS_WATERMILL', 'YIELD_CULTURE', 2 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_KYZYL', 'BUILDINGCLASS_PALACE', 'YIELD_TOURISM', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_KYZYL', 'BUILDINGCLASS_MONUMENT', 'YIELD_TOURISM', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LA_VENTA', 'BUILDINGCLASS_SHRINE', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MONACO', 'BUILDINGCLASS_MARKET', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MONACO', 'BUILDINGCLASS_BANK', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_PRAGUE', 'BUILDINGCLASS_WALLS', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_PRAGUE', 'BUILDINGCLASS_CASTLE', 'YIELD_CULTURE', 1;

INSERT INTO EventChoice_ImprovementYieldChange (EventChoiceType, ImprovementType, YieldType, YieldChange)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BYBLOS', 'IMPROVEMENT_FISHING_BOATS', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_CAHOKIA', 'IMPROVEMENT_MOUND', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_CAHOKIA', 'IMPROVEMENT_MOUND', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_COLOMBO', 'IMPROVEMENT_LUMBERMILL', 'YIELD_GOLD', -2 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_COLOMBO', 'IMPROVEMENT_LUMBERMILL_JUNGLE', 'YIELD_GOLD', -2 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_FLORENCE', 'IMPROVEMENT_QUARRY', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LA_VENTA', 'IMPROVEMENT_ACADEMY', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LA_VENTA', 'IMPROVEMENT_HOLY_SITE', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LA_VENTA', 'IMPROVEMENT_CUSTOMS_HOUSE', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LA_VENTA', 'IMPROVEMENT_CUSTOMS_HOUSE_VENICE', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LA_VENTA', 'IMPROVEMENT_MANUFACTORY', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LA_VENTA', 'IMPROVEMENT_CITADEL', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LA_VENTA', 'IMPROVEMENT_EMBASSY', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MELBOURNE', 'IMPROVEMENT_MINE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MELBOURNE', 'IMPROVEMENT_ACADEMY', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MELBOURNE', 'IMPROVEMENT_HOLY_SITE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MELBOURNE', 'IMPROVEMENT_CUSTOMS_HOUSE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MELBOURNE', 'IMPROVEMENT_CUSTOMS_HOUSE_VENICE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MELBOURNE', 'IMPROVEMENT_MANUFACTORY', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MELBOURNE', 'IMPROVEMENT_CITADEL', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MELBOURNE', 'IMPROVEMENT_EMBASSY', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_PANAMA_CITY', 'IMPROVEMENT_FORT', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_PANAMA_CITY', 'IMPROVEMENT_CITADEL', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_PANAMA_CITY', 'IMPROVEMENT_PONTOON_BRIDGE', 'YIELD_FOOD', 1 WHERE EXISTS (SELECT * FROM Improvements WHERE Type='IMPROVEMENT_PONTOON_BRIDGE') UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_QUEBEC_CITY', 'IMPROVEMENT_CAMP', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_QUEBEC_CITY', 'IMPROVEMENT_LUMBERMILL', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_QUEBEC_CITY', 'IMPROVEMENT_LUMBERMILL_JUNGLE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_RAGUSA', 'IMPROVEMENT_EMBASSY', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_TYRE', 'IMPROVEMENT_LANDMARK', 'YIELD_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VANCOUVER', 'IMPROVEMENT_TRADING_POST', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VANCOUVER', 'IMPROVEMENT_ACADEMY', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VANCOUVER', 'IMPROVEMENT_HOLY_SITE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VANCOUVER', 'IMPROVEMENT_CUSTOMS_HOUSE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VANCOUVER', 'IMPROVEMENT_CUSTOMS_HOUSE_VENICE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VANCOUVER', 'IMPROVEMENT_MANUFACTORY', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VANCOUVER', 'IMPROVEMENT_CITADEL', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_VANCOUVER', 'IMPROVEMENT_EMBASSY', 'YIELD_FOOD', 1;

INSERT INTO EventChoice_FeatureYieldChange (EventChoiceType, FeatureType, YieldType, YieldChange)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BRUSSELS', 'FEATURE_MARSH', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BYBLOS', 'FEATURE_OASIS', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_COLOMBO', 'FEATURE_FOREST', 'YIELD_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_COLOMBO', 'FEATURE_JUNGLE', 'YIELD_GOLD', 2 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MOGADISHU', 'FEATURE_FLOOD_PLAINS', 'YIELD_FOOD', 1;

INSERT INTO EventChoice_TerrainYieldChange (EventChoiceType, TerrainType, YieldType, YieldChange)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MOGADISHU', 'TERRAIN_OCEAN', 'YIELD_FOOD', 1;

INSERT INTO EventChoice_ResourceYieldChange (EventChoiceType, ResourceType, YieldType, YieldChange)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUENOS_AIRES', 'RESOURCE_WHEAT', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUENOS_AIRES', 'RESOURCE_COW', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUENOS_AIRES', 'RESOURCE_SHEEP', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUENOS_AIRES', 'RESOURCE_DEER', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUENOS_AIRES', 'RESOURCE_BANANA', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUENOS_AIRES', 'RESOURCE_FISH', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUENOS_AIRES', 'RESOURCE_STONE', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_BUENOS_AIRES', 'RESOURCE_BISON', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_WHALE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_PEARLS', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_GOLD', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_SILVER', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_GEMS', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_MARBLE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_IVORY', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_FUR', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_DYE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_SPICES', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_SILK', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_SUGAR', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_COTTON', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_WINE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_INCENSE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_JEWELRY', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_PORCELAIN', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_COPPER', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_SALT', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_CRAB', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_TRUFFLES', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_CITRUS', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_NUTMEG', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_CLOVES', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_PEPPER', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_COCOA', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_COFFEE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_TEA', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_TOBACCO', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_AMBER', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_JADE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_OLIVE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_PERFUME', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_CORAL', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_LAPIS', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MALACCA', 'RESOURCE_GLASS', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MOMBASA', 'RESOURCE_WHEAT', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MOMBASA', 'RESOURCE_COW', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MOMBASA', 'RESOURCE_SHEEP', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MOMBASA', 'RESOURCE_DEER', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MOMBASA', 'RESOURCE_BANANA', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MOMBASA', 'RESOURCE_FISH', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MOMBASA', 'RESOURCE_STONE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MOMBASA', 'RESOURCE_BISON', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_WHALE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_PEARLS', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_GOLD', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_SILVER', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_GEMS', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_MARBLE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_IVORY', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_FUR', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_DYE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_SPICES', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_SILK', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_SUGAR', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_COTTON', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_WINE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_INCENSE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_JEWELRY', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_PORCELAIN', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_COPPER', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_SALT', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_CRAB', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_TRUFFLES', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_CITRUS', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_NUTMEG', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_CLOVES', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_PEPPER', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_COCOA', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_COFFEE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_TEA', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_TOBACCO', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_AMBER', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_JADE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_OLIVE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_PERFUME', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_CORAL', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_LAPIS', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ORMUS', 'RESOURCE_GLASS', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_WELLINGTON', 'RESOURCE_IRON', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_WELLINGTON', 'RESOURCE_HORSE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_WELLINGTON', 'RESOURCE_COAL', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_WELLINGTON', 'RESOURCE_OIL', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_WELLINGTON', 'RESOURCE_ALUMINUM', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_WELLINGTON', 'RESOURCE_URANIUM', 'YIELD_FOOD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'RESOURCE_WHEAT', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'RESOURCE_COW', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'RESOURCE_SHEEP', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'RESOURCE_DEER', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'RESOURCE_BANANA', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'RESOURCE_FISH', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'RESOURCE_STONE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'RESOURCE_BISON', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'RESOURCE_IRON', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'RESOURCE_HORSE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'RESOURCE_COAL', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'RESOURCE_OIL', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'RESOURCE_ALUMINUM', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ZANZIBAR', 'RESOURCE_URANIUM', 'YIELD_GOLD', 1;

INSERT INTO EventChoice_CityUnhappinessNeedMod (EventChoiceType, YieldType, Yield)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_WITTENBERG', 'YIELD_FAITH', -15;

INSERT INTO Builds (Type, Time, ImprovementType, Description, Help, EntityEvent, HotKey, OrderPriority, IconIndex, IconAtlas)
SELECT 'BUILD_MARSH', 700, 'IMPROVEMENT_MARSH', 'TXT_KEY_BUILD_MARSH', 'TXT_KEY_BUILD_MARSH_HELP', 'ENTITY_EVENT_IRRIGATE', 'KB_L', 97, 0, 'EXPANSION_UNIT_ACTION_ATLAS' UNION ALL
SELECT 'BUILD_MOUND', 700, 'IMPROVEMENT_MOUND', 'TXT_KEY_BUILD_MOUND', 'TXT_KEY_BUILD_MOUND_HELP', 'ENTITY_EVENT_BUILD', 'KB_F', 1, 0, 'UNIT_ACTION_KUNA';

INSERT INTO Unit_Builds (UnitType, BuildType)
SELECT 'UNIT_WORKER', 'BUILD_MARSH' UNION ALL
SELECT 'UNIT_WORKER', 'BUILD_MOUND';

INSERT INTO BuildFeatures (BuildType, FeatureType, PrereqTech, Time, Production, Remove)
SELECT 'BUILD_MARSH', 'FEATURE_JUNGLE', 'TECH_IRON_WORKING', 500, 20, 1 UNION ALL
SELECT 'BUILD_MARSH', 'FEATURE_FOREST', 'TECH_BRONZE_WORKING', 300, 20, 1 UNION ALL
SELECT 'BUILD_MOUND', 'FEATURE_FOREST', 'TECH_BRONZE_WORKING', 300, 20, 1 UNION ALL
SELECT 'BUILD_MOUND', 'FEATURE_JUNGLE', 'TECH_IRON_WORKING', 500, 20, 1 UNION ALL
SELECT 'BUILD_MOUND', 'FEATURE_MARSH', 'TECH_MACHINERY', 600, 0, 1;

INSERT INTO Improvements (Type, Description, Civilopedia, Help, ArtDefineTag, PortraitIndex, IconAtlas)
SELECT 'IMPROVEMENT_MARSH', 'TXT_KEY_IMPROVEMENT_MARSH', 'TXT_KEY_CIV5_IMPROVEMENTS_MARSH', 'TXT_KEY_IMPROVEMENT_MARSH_HELP', 'ART_DEF_IMPROVEMENT_POLDER', 0, 'EXPANSION_TERRAIN_ATLAS' UNION ALL
SELECT 'IMPROVEMENT_MOUND', 'TXT_KEY_IMPROVEMENT_MOUND', 'TXT_KEY_CIV5_IMPROVEMENTS_MOUND', 'TXT_KEY_IMPROVEMENT_MOUND_HELP', 'ART_DEF_IMPROVEMENT_MOTTE_BAILEY', 0, 'TERRAIN_IMPROVEMENT_KUNA';

UPDATE Improvements
SET Coastal = 1
WHERE Type = 'IMPROVEMENT_MARSH';

UPDATE Improvements
SET NoTwoAdjacent = 1, DefenseModifier = 15
WHERE Type = 'IMPROVEMENT_MOUND';

UPDATE ArtDefine_Landmarks
SET Scale= 0.75
WHERE ImprovementType = 'ART_DEF_IMPROVEMENT_MOTTE_BAILEY';

INSERT INTO Improvement_ValidTerrains (ImprovementType, TerrainType)
SELECT 'IMPROVEMENT_MARSH', 'TERRAIN_DESERT' UNION ALL
SELECT 'IMPROVEMENT_MARSH', 'TERRAIN_TUNDRA' UNION ALL
SELECT 'IMPROVEMENT_MARSH', 'TERRAIN_SNOW' UNION ALL
SELECT 'IMPROVEMENT_MOUND', 'TERRAIN_GRASS' UNION ALL
SELECT 'IMPROVEMENT_MOUND', 'TERRAIN_PLAINS' UNION ALL
SELECT 'IMPROVEMENT_MOUND', 'TERRAIN_DESERT' UNION ALL
SELECT 'IMPROVEMENT_MOUND', 'TERRAIN_TUNDRA' UNION ALL
SELECT 'IMPROVEMENT_MOUND', 'TERRAIN_SNOW';
	
INSERT INTO Improvement_Yields (ImprovementType, YieldType, Yield)
SELECT 'IMPROVEMENT_MARSH', 'YIELD_FOOD', 1 UNION ALL
SELECT 'IMPROVEMENT_MOUND', 'YIELD_GOLD', 1;

INSERT INTO Improvement_AdjacentImprovementYieldChanges (ImprovementType, OtherImprovementType, YieldType, Yield)
SELECT 'IMPROVEMENT_MOUND', 'IMPROVEMENT_TRADING_POST', 'YIELD_GOLD', 1 UNION ALL
SELECT 'IMPROVEMENT_MOUND', 'IMPROVEMENT_TRADING_POST', 'YIELD_FAITH', 1;

INSERT INTO Improvement_AdjacentCityYields (ImprovementType, YieldType, Yield)
SELECT 'IMPROVEMENT_MOUND', 'YIELD_GOLDEN_AGE_POINTS', 1;

INSERT INTO Policy_ImprovementYieldChanges (PolicyType, ImprovementType, YieldType, Yield)
SELECT 'POLICY_URBANIZATION', 'IMPROVEMENT_MOUND', 'YIELD_FOOD', 2 UNION ALL
SELECT 'POLICY_MOBILIZATION', 'IMPROVEMENT_MOUND', 'YIELD_SCIENCE', 3 UNION ALL
SELECT 'POLICY_FIVE_YEAR_PLAN', 'IMPROVEMENT_MOUND', 'YIELD_PRODUCTION', 1 UNION ALL
SELECT 'POLICY_URBANIZATION', 'IMPROVEMENT_MARSH', 'YIELD_FOOD', 2 UNION ALL
SELECT 'POLICY_MOBILIZATION', 'IMPROVEMENT_MARSH', 'YIELD_SCIENCE', 3 UNION ALL
SELECT 'POLICY_FIVE_YEAR_PLAN', 'IMPROVEMENT_MARSH', 'YIELD_PRODUCTION', 1;