INSERT INTO Language_en_US (Tag, Text)
SELECT 'TXT_KEY_CITYSTATE_CLERMONT', 'Clermont' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_CLERMONT_ADJ', 'The Clermont' UNION ALL
SELECT 'TXT_KEY_CIV5_CLERMONT_TEXT', 'Clermont was the starting point of the First Crusade, in which Christendom sought to free Jerusalem from Muslim domination: Pope Urban II preached the crusade in 1095 at the Second Council of Clermont.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_HONDURAS', 'Honduras' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_HONDURAS_ADJ', 'Honduran' UNION ALL
SELECT 'TXT_KEY_CIV5_HONDURAS_TEXT', 'Honduras was home to several Mesoamerican cultures before the Spanish took over in the 16th century. Honduras became independent in 1821 and has since been a republic. However the republic remains a figure of a banana republic where their government encouraged developments from foreign investors which these developments came out with bananas.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_AUCKLAND', 'Auckland' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_AUCKLAND_ADJ', 'The Auckland' UNION ALL
SELECT 'TXT_KEY_CIV5_AUCKLAND_TEXT', 'When the Maori settled upon an isthmus in what is now northern New Zealand, they found the surrounding landscape full of fertile land, lush jungle, and dormant volcanos. Protected natural harbors on either side of the isthmus offered plentiful fishing and a base for war canoes (''waka taua''). The settlers named it ''Tamaki Makaurau''—roughly translating to "the maiden sought by a hundred lovers."' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ARMAGH', 'Armagh' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ARMAGH_ADJ', 'The Armagh' UNION ALL
SELECT 'TXT_KEY_CIV5_ARMAGH_TEXT', 'The Irish town of Armagh has long known religion. Thought to have been a worship site for ancient pagans, it gained prominence in the 5th Century when Saint Patrick, a Christian missionary, constructed and consecrated a stone church on the summit of a hill. Around that sprang a monastery, and then a town devoted to spreading Christianity throughout Ireland—a beachhead of theology.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MUSCAT', 'Muscat' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MUSCAT_ADJ', 'The Muscat' UNION ALL
SELECT 'TXT_KEY_CIV5_MUSCAT_TEXT', 'The trade flowing through Muscat has been its lifeblood for at least two millennia. Nestled against the foothillls of the Al Hajar mountains, Ptolemy called it the Hidden Port (''Cryptus Portus'') as early as the 1st Century. Unfortunately the city was not hidden well enough—its prime location at the mouth of the Persian Gulf has long since made it a tempting target for conquest.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_GRANADA', 'Granada' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_GRANADA_ADJ', 'The Granada' UNION ALL
SELECT 'TXT_KEY_CIV5_GRANADA_TEXT', 'In the 8th Century the Umayyad Caliphate spread through the Iberian Peninsula, rapidly conquering Visigothic Hispania. Granada, a fortified settlement in what is now southern Spain, was swept up in the invasion. In time to come (the late 15th Century, to be exact) its surrender to the Catholic Monarchs (''Los Reyes Católicos'') would end the Reconquista of Andalusia—but for three quarters of a millennium, Granada belonged to the Moors.
Located at the base of the Sierra Nevada range, Granada had the misfortune of being nearly indefensible due to its location on a low-lying plain. Its Moorish rulers quickly realized this and transferred their seat of power to the more defensible foothills overlooking the town. Part of their plans involved the building of alcazars, one of which would in later years be renovated into the beautiful Alhambra.
Granada''s Moorish masters shifted through the centuries. The Almohad replaced the Almoravids, who had themselves succeeded the remnants of the Umayyad. The city''s fortunes changed again in the 13th Century with the Nasrid dynasty, whose alliance with the Catholic kingdom of Castile led to the Emirate of Granada. Direct access to trade centers in sub-Saharan Africa bought Granada freedom from the Reconquista—for a time.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_NANMANDOL', 'Leluh' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_NANMANDOL_ADJ', 'The Leluh' UNION ALL
SELECT 'TXT_KEY_CIV5_NANMANDOL_TEXT', 'Leluh is a major prehistoric and historic archaeological site. The remains are those of a civilization that peaked around the 14th and 15th centuries, with elements still visible at the time of European contact in the early 19th century. The rulers of Leluh gradually conquered and thus unified the island of Kosrae. From the capital at Leluh, they ruled the island with a monarchy that archaeologists believe was similar to the kingdoms of Tonga or Hawaii.' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT', '[COLOR:224:255:61:255]Crusader''s Zeal[ENDCOLOR]: Newly-produced Melee and Gun Units receive a random 10 Turn Promotion bonus upon their first combat and Military Units generate +33% Experience gained from combat.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_HONDURAS', '[COLOR:224:255:61:255]Banana Republic[ENDCOLOR]: Resources from City-States count toward Global Monopolies.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_AUCKLAND', '[COLOR:224:255:61:255]Tamaki Makaurau[ENDCOLOR]: +3 [ICON_FOOD] Food to Coastal Cities.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ARMAGH', '[COLOR:224:255:61:255]Patron of Saints[ENDCOLOR]: May faith-purchase Saints (Requires a Majority Religion).[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MUSCAT', '[COLOR:224:255:61:255]Cryptus Portus[ENDCOLOR]: Lighthouses, Harbors, and Seaports produce +1 [ICON_GOLD] Gold.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_GRANADA', '[COLOR:224:255:61:255]Alcázars[ENDCOLOR]: Forts and Citadels produce +1 [ICON_CULTURE] Culture.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_NANMANDOL', '[COLOR:224:255:61:255]Reef of Heaven[ENDCOLOR]: +1 [ICON_CULTURE] Culture to Oceans.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT0', 'Crusader''s Zeal' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT0_HELP', '+33% Experience gained from Combat.' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT1', 'Blessing of Clermont' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT1_HELP', 'Receive a temporary random combat bonus upon the first combat.' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT2', 'Onward with Haste!' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT2_HELP', '+2 [ICON_MOVES] Moves. Can move after attacking.' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT3', 'United We Stand!' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT3_HELP', '+25% [ICON_STRENGTH] Combat Strength when adjacent to a friendly unit.' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT4', 'Charge!' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT4_HELP', '+15% [ICON_STRENGTH] Attack. +25% [ICON_STRENGTH] against Fortified Units.' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT5', 'Reinforce!' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT5_HELP', '+15% [ICON_STRENGTH] Defense. Can heal after attacking.' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT6', 'Glory to God!' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT6_HELP', 'Unit awards combat bonus to nearby units as if it is a Great General. This unit and all others in adjacent tiles heal 5 additional HP per turn.' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH1', 'Saint Patricius' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH1_HELP', 'Reduces [ICON_HAPPINESS_3] Boredom. Requires an alliance with [COLOR_POSITIVE_TEXT]Armagh[ENDCOLOR]. Culture bonus lost without the alliance. Can never be destroyed.' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH2', 'Saint Benignus' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH2_HELP', 'Reduces [ICON_HAPPINESS_3] Illiteracy. Requires an alliance with [COLOR_POSITIVE_TEXT]Armagh[ENDCOLOR]. Science bonus lost without the alliance. Can never be destroyed.' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH3', 'Saint Secundinus' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH3_HELP', 'Reduces [ICON_HAPPINESS_3] Poverty. Requires an alliance with [COLOR_POSITIVE_TEXT]Armagh[ENDCOLOR]. Gold bonus lost without the alliance. Can never be destroyed.' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH4', 'Saint Celestinus' UNION ALL
SELECT 'TXT_KEY_BUILDING_ARMAGH4_HELP', 'Reduces [ICON_HAPPINESS_3] Distress. Requires an alliance with [COLOR_POSITIVE_TEXT]Armagh[ENDCOLOR]. Food/Production bonus lost without the alliance. Can never be destroyed.';

INSERT INTO MinorCivilizations (Type, ShortDescription, Civilopedia, Description, Adjective, ArtDefineTag, DefaultPlayerColor, ArtStyleType, ArtStyleSuffix, ArtStylePrefix, MinorCivTrait)
SELECT 'MINOR_CIV_CLERMONT', 'TXT_KEY_CITYSTATE_CLERMONT', 'TXT_KEY_CIV5_CLERMONT_TEXT', 'TXT_KEY_CITYSTATE_CLERMONT', 'TXT_KEY_CITYSTATE_CLERMONT_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_CYAN', 'ARTSTYLE_EUROPEAN', '_EURO', 'EUROPEAN', 'MINOR_TRAIT_MILITARISTIC' UNION ALL
SELECT 'MINOR_CIV_HONDURAS', 'TXT_KEY_CITYSTATE_HONDURAS', 'TXT_KEY_CIV5_HONDURAS_TEXT', 'TXT_KEY_CITYSTATE_HONDURAS', 'TXT_KEY_CITYSTATE_HONDURAS_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_YELLOW', 'ARTSTYLE_SOUTH_AMERICA', '_AMER', 'AMERICAN', 'MINOR_TRAIT_MERCANTILE' UNION ALL
SELECT 'MINOR_CIV_AUCKLAND', 'TXT_KEY_CITYSTATE_AUCKLAND', 'TXT_KEY_CIV5_AUCKLAND_TEXT', 'TXT_KEY_CITYSTATE_AUCKLAND', 'TXT_KEY_CITYSTATE_AUCKLAND_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_GREEN', 'ARTSTYLE_ASIAN', '_ASIA', 'ASIAN', 'MINOR_TRAIT_MARITIME' UNION ALL
SELECT 'MINOR_CIV_ARMAGH', 'TXT_KEY_CITYSTATE_ARMAGH', 'TXT_KEY_CIV5_ARMAGH_TEXT', 'TXT_KEY_CITYSTATE_ARMAGH', 'TXT_KEY_CITYSTATE_ARMAGH_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_WHITE', 'ARTSTYLE_EUROPEAN', '_EURO', 'EUROPEAN', 'MINOR_TRAIT_RELIGIOUS' UNION ALL
SELECT 'MINOR_CIV_MUSCAT', 'TXT_KEY_CITYSTATE_MUSCAT', 'TXT_KEY_CIV5_MUSCAT_TEXT', 'TXT_KEY_CITYSTATE_MUSCAT', 'TXT_KEY_CITYSTATE_MUSCAT_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_YELLOW', 'ARTSTYLE_MIDDLE_EAST', '_AFRI', 'AFRICAN', 'MINOR_TRAIT_MERCANTILE' UNION ALL
SELECT 'MINOR_CIV_GRANADA', 'TXT_KEY_CITYSTATE_GRANADA', 'TXT_KEY_CIV5_GRANADA_TEXT', 'TXT_KEY_CITYSTATE_GRANADA', 'TXT_KEY_CITYSTATE_GRANADA_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_CYAN', 'ARTSTYLE_EUROPEAN', '_EURO', 'EUROPEAN', 'MINOR_TRAIT_MILITARISTIC' UNION ALL
SELECT 'MINOR_CIV_NANMANDOL', 'TXT_KEY_CITYSTATE_NANMANDOL', 'TXT_KEY_CIV5_NANMANDOL_TEXT', 'TXT_KEY_CITYSTATE_NANMANDOL', 'TXT_KEY_CITYSTATE_NANMANDOL_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_PURPLE', 'ARTSTYLE_ASIAN', '_ASIA', 'ASIAN', 'MINOR_TRAIT_CULTURED';

INSERT INTO MinorCivilization_CityNames (MinorCivType, CityName)
SELECT 'MINOR_CIV_CLERMONT', 'TXT_KEY_CITYSTATE_CLERMONT' UNION ALL
SELECT 'MINOR_CIV_HONDURAS', 'TXT_KEY_CITYSTATE_HONDURAS' UNION ALL
SELECT 'MINOR_CIV_AUCKLAND', 'TXT_KEY_CITYSTATE_AUCKLAND' UNION ALL
SELECT 'MINOR_CIV_ARMAGH', 'TXT_KEY_CITYSTATE_ARMAGH' UNION ALL
SELECT 'MINOR_CIV_MUSCAT', 'TXT_KEY_CITYSTATE_MUSCAT' UNION ALL
SELECT 'MINOR_CIV_GRANADA', 'TXT_KEY_CITYSTATE_GRANADA' UNION ALL
SELECT 'MINOR_CIV_NANMANDOL', 'TXT_KEY_CITYSTATE_NANMANDOL';

INSERT INTO MinorCivilization_Flavors (MinorCivType, FlavorType, Flavor)
SELECT 'MINOR_CIV_CLERMONT', 'FLAVOR_OFFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_CLERMONT', 'FLAVOR_DEFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_CLERMONT', 'FLAVOR_MILITARY_TRAINING', 7 UNION ALL
SELECT 'MINOR_CIV_CLERMONT', 'FLAVOR_CITY_DEFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_CLERMONT', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_CLERMONT', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_CLERMONT', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_HONDURAS', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_HONDURAS', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_HONDURAS', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_HONDURAS', 'FLAVOR_GOLD', 10 UNION ALL
SELECT 'MINOR_CIV_AUCKLAND', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_AUCKLAND', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_AUCKLAND', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_AUCKLAND', 'FLAVOR_GROWTH', 8 UNION ALL
SELECT 'MINOR_CIV_AUCKLAND', 'FLAVOR_NAVAL', 8 UNION ALL
SELECT 'MINOR_CIV_ARMAGH', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_ARMAGH', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_ARMAGH', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_ARMAGH', 'FLAVOR_RELIGION', 10 UNION ALL
SELECT 'MINOR_CIV_MUSCAT', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_MUSCAT', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_MUSCAT', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_MUSCAT', 'FLAVOR_GOLD', 10 UNION ALL
SELECT 'MINOR_CIV_GRANADA', 'FLAVOR_OFFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_GRANADA', 'FLAVOR_DEFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_GRANADA', 'FLAVOR_MILITARY_TRAINING', 7 UNION ALL
SELECT 'MINOR_CIV_GRANADA', 'FLAVOR_CITY_DEFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_GRANADA', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_GRANADA', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_GRANADA', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_NANMANDOL', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_NANMANDOL', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_NANMANDOL', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_NANMANDOL', 'FLAVOR_CULTURE', 10;

INSERT INTO UnitPromotions (Type, Description, Help, CannotBeChosen, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry)
SELECT 'PROMOTION_CLERMONT', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT0', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT0_HELP', 1, 'AS2D_IF_LEVELUP', 0, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT0' UNION ALL
SELECT 'PROMOTION_CLERMONT1', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT1', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT1_HELP', 1, 'AS2D_IF_LEVELUP', 1, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT1' UNION ALL
SELECT 'PROMOTION_CLERMONT2', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT2', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT2_HELP', 1, 'AS2D_IF_LEVELUP', 2, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT2' UNION ALL
SELECT 'PROMOTION_CLERMONT3', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT3', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT3_HELP', 1, 'AS2D_IF_LEVELUP', 3, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT3' UNION ALL
SELECT 'PROMOTION_CLERMONT4', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT4', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT4_HELP', 1, 'AS2D_IF_LEVELUP', 4, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT4' UNION ALL
SELECT 'PROMOTION_CLERMONT5', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT5', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT5_HELP', 1, 'AS2D_IF_LEVELUP', 5, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT5' UNION ALL
SELECT 'PROMOTION_CLERMONT6', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT6', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT6_HELP', 1, 'AS2D_IF_LEVELUP', 6, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT6';

UPDATE UnitPromotions
SET ExperiencePercent = 33
WHERE Type = 'PROMOTION_CLERMONT';

UPDATE UnitPromotions
SET HasPostCombatPromotions = 1
WHERE Type = 'PROMOTION_CLERMONT1';

UPDATE UnitPromotions
SET MovesChange = 2, CanMoveAfterAttacking = 1, PromotionDuration = 10
WHERE Type = 'PROMOTION_CLERMONT2';

UPDATE UnitPromotions
SET AdjacentMod = 25, PromotionDuration = 10
WHERE Type = 'PROMOTION_CLERMONT3';

UPDATE UnitPromotions
SET AttackMod = 15, AttackFortifiedMod = 25, PromotionDuration = 10
WHERE Type = 'PROMOTION_CLERMONT4';

UPDATE UnitPromotions
SET DefenseMod = 15, AlwaysHeal = 1, PromotionDuration = 10
WHERE Type = 'PROMOTION_CLERMONT5';

UPDATE UnitPromotions
SET GreatGeneral = 1, SameTileHealChange = 5, AdjacentTileHealChange = 5, PromotionDuration = 10
WHERE Type = 'PROMOTION_CLERMONT6';

INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT 'PROMOTION_CLERMONT', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_CLERMONT', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_CLERMONT', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_CLERMONT', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_CLERMONT', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_CLERMONT', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_CLERMONT', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_CLERMONT', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_CLERMONT', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_CLERMONT', 'UNITCOMBAT_NAVALRANGED' UNION ALL
SELECT 'PROMOTION_CLERMONT1', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_CLERMONT1', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_CLERMONT2', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_CLERMONT2', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_CLERMONT3', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_CLERMONT3', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_CLERMONT4', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_CLERMONT4', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_CLERMONT5', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_CLERMONT5', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_CLERMONT6', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_CLERMONT6', 'UNITCOMBAT_GUN';

INSERT INTO UnitPromotions_PostCombatRandomPromotion (PromotionType, NewPromotion)
SELECT 'PROMOTION_CLERMONT1', 'PROMOTION_CLERMONT2' UNION ALL
SELECT 'PROMOTION_CLERMONT1', 'PROMOTION_CLERMONT3' UNION ALL
SELECT 'PROMOTION_CLERMONT1', 'PROMOTION_CLERMONT4' UNION ALL
SELECT 'PROMOTION_CLERMONT1', 'PROMOTION_CLERMONT5' UNION ALL
SELECT 'PROMOTION_CLERMONT1', 'PROMOTION_CLERMONT6';

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
SELECT 'BUILDINGCLASS_CLERMONT', 'BUILDING_CLERMONT', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT0' UNION ALL
SELECT 'BUILDINGCLASS_ARMAGH1', 'BUILDING_ARMAGH1', 'TXT_KEY_BUILDING_ARMAGH1' UNION ALL
SELECT 'BUILDINGCLASS_ARMAGH2', 'BUILDING_ARMAGH2', 'TXT_KEY_BUILDING_ARMAGH2' UNION ALL
SELECT 'BUILDINGCLASS_ARMAGH3', 'BUILDING_ARMAGH3', 'TXT_KEY_BUILDING_ARMAGH3' UNION ALL
SELECT 'BUILDINGCLASS_ARMAGH4', 'BUILDING_ARMAGH4', 'TXT_KEY_BUILDING_ARMAGH4';

INSERT INTO Buildings (Type, BuildingClass, Cost, GoldMaintenance, PrereqTech, Description, Help, MinAreaSize, NukeImmune, ConquestProb, NeverCapture, HurryCostModifier, IconAtlas, PortraitIndex, IsDummy)
SELECT 'BUILDING_CLERMONT', 'BUILDINGCLASS_CLERMONT', -1, 0, NULL, 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT0', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT', -1, 1, 0, 1, 5, 'UCS_ATLAS', 1, 1 UNION ALL
SELECT 'BUILDING_ARMAGH1', 'BUILDINGCLASS_ARMAGH1', -1, 0, NULL, 'TXT_KEY_BUILDING_ARMAGH1', 'TXT_KEY_BUILDING_ARMAGH1_HELP', -1, 1, 0, 1, 5, 'UCS_ATLAS', 1, 0 UNION ALL
SELECT 'BUILDING_ARMAGH2', 'BUILDINGCLASS_ARMAGH2', -1, 0, NULL, 'TXT_KEY_BUILDING_ARMAGH2', 'TXT_KEY_BUILDING_ARMAGH2_HELP', -1, 1, 0, 1, 5, 'UCS_ATLAS', 1, 0 UNION ALL
SELECT 'BUILDING_ARMAGH3', 'BUILDINGCLASS_ARMAGH3', -1, 0, NULL, 'TXT_KEY_BUILDING_ARMAGH3', 'TXT_KEY_BUILDING_ARMAGH3_HELP', -1, 1, 0, 1, 5, 'UCS_ATLAS', 1, 0 UNION ALL
SELECT 'BUILDING_ARMAGH4', 'BUILDINGCLASS_ARMAGH4', -1, 0, NULL, 'TXT_KEY_BUILDING_ARMAGH4', 'TXT_KEY_BUILDING_ARMAGH4_HELP', -1, 1, 0, 1, 5, 'UCS_ATLAS', 1, 0;

UPDATE Buildings
SET TrainedFreePromotion = 'PROMOTION_CLERMONT1'
WHERE Type = 'BUILDING_CLERMONT';

UPDATE Buildings
SET FaithCost = 250, WLTKDTurns = 10, EventChoiceRequiredActive = 'PLAYER_EVENT_CHOICE_MINOR_CIV_ARMAGH', UnculturedHappinessChange = -5, MutuallyExclusiveGroup = 113
WHERE Type = 'BUILDING_ARMAGH1';

UPDATE Buildings
SET FaithCost = 250, WLTKDTurns = 10, EventChoiceRequiredActive = 'PLAYER_EVENT_CHOICE_MINOR_CIV_ARMAGH', IlliteracyHappinessChange = -5, MutuallyExclusiveGroup = 113
WHERE Type = 'BUILDING_ARMAGH2';

UPDATE Buildings
SET FaithCost = 250, WLTKDTurns = 10, EventChoiceRequiredActive = 'PLAYER_EVENT_CHOICE_MINOR_CIV_ARMAGH', PovertyHappinessChange = -5, MutuallyExclusiveGroup = 113
WHERE Type = 'BUILDING_ARMAGH3';

UPDATE Buildings
SET FaithCost = 250, WLTKDTurns = 10, EventChoiceRequiredActive = 'PLAYER_EVENT_CHOICE_MINOR_CIV_ARMAGH', DefenseHappinessChange = -5, MutuallyExclusiveGroup = 113
WHERE Type = 'BUILDING_ARMAGH4';

INSERT INTO Policies (Type, Description)
SELECT 'POLICY_HONDURAS', 'TXT_KEY_CITYSTATE_HONDURAS' UNION ALL
SELECT 'POLICY_AUCKLAND', 'TXT_KEY_CITYSTATE_AUCKLAND';

UPDATE Policies
SET CSResourcesCountForMonopolies = 1
WHERE Type = 'POLICY_HONDURAS';

INSERT INTO Policy_CoastalCityYieldChanges (PolicyType, YieldType, Yield)
SELECT 'POLICY_AUCKLAND', 'YIELD_FOOD', 3;

INSERT INTO Events (Type, Description, Help, EventArt, RandomChance, NumChoices, IgnoresGlobalCooldown, EventCooldown)
SELECT  'PLAYER_EVENT_MINOR_CIV_CLERMONT', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_HONDURAS', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_HONDURAS', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_AUCKLAND', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_AUCKLAND', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_ARMAGH', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ARMAGH', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_MUSCAT', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MUSCAT', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_GRANADA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_GRANADA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_NANMANDOL', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_NANMANDOL', 'AllianceShift.dds', -1, 1, 1, 1;

INSERT INTO EventChoices (Type, Description, Help, EventDuration, Expires, EventPolicy, EventPromotion, EventBuildingClassGlobal)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_CLERMONT', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_CLERMONT', 3, 1, NULL, 'PROMOTION_CLERMONT', 'BUILDINGCLASS_CLERMONT' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_HONDURAS', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_HONDURAS', 3, 1, 'POLICY_HONDURAS', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_AUCKLAND', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_AUCKLAND', 3, 1, 'POLICY_AUCKLAND', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ARMAGH', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ARMAGH', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MUSCAT', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MUSCAT', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_GRANADA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_GRANADA', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_NANMANDOL', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_NANMANDOL', 3, 1, NULL, NULL, NULL;

INSERT INTO Event_ParentEvents (EventChoiceType, EventType)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_CLERMONT', 'PLAYER_EVENT_MINOR_CIV_CLERMONT' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_HONDURAS', 'PLAYER_EVENT_MINOR_CIV_HONDURAS' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_AUCKLAND', 'PLAYER_EVENT_MINOR_CIV_AUCKLAND' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ARMAGH', 'PLAYER_EVENT_MINOR_CIV_ARMAGH' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MUSCAT', 'PLAYER_EVENT_MINOR_CIV_MUSCAT' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_GRANADA', 'PLAYER_EVENT_MINOR_CIV_GRANADA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_NANMANDOL', 'PLAYER_EVENT_MINOR_CIV_NANMANDOL';

INSERT INTO EventChoice_ImprovementYieldChange (EventChoiceType, ImprovementType, YieldType, YieldChange)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_GRANADA', 'IMPROVEMENT_FORT', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_GRANADA', 'IMPROVEMENT_CITADEL', 'YIELD_CULTURE', 1;

INSERT INTO EventChoice_TerrainYieldChange (EventChoiceType, TerrainType, YieldType, YieldChange)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_NANMANDOL', 'TERRAIN_OCEAN', 'YIELD_CULTURE', 1;

INSERT INTO EventChoice_BuildingClassYieldModifier (EventChoiceType, BuildingClassType, YieldType, Modifier)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ARMAGH', 'BUILDINGCLASS_ARMAGH1', 'YIELD_CULTURE', 5 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ARMAGH', 'BUILDINGCLASS_ARMAGH2', 'YIELD_SCIENCE', 5 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ARMAGH', 'BUILDINGCLASS_ARMAGH3', 'YIELD_GOLD', 5 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ARMAGH', 'BUILDINGCLASS_ARMAGH4', 'YIELD_FOOD', 3 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ARMAGH', 'BUILDINGCLASS_ARMAGH4', 'YIELD_PRODUCTION', 3 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MUSCAT', 'BUILDINGCLASS_LIGHTHOUSE', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MUSCAT', 'BUILDINGCLASS_HARBOR', 'YIELD_GOLD', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MUSCAT', 'BUILDINGCLASS_SEAPORT', 'YIELD_GOLD', 1;

INSERT INTO EventChoice_BuildingClassYieldChange (EventChoiceType, BuildingClassType, YieldType, YieldChange)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_HONDURAS', 'BUILDINGCLASS_HARBOR', 'YIELD_GOLD', 1;
