INSERT INTO Language_en_US (Tag, Text)
SELECT 'TXT_KEY_CITYSTATE_GWYNEDD', 'Gwynedd' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_GWYNEDD_ADJ', 'Welsh' UNION ALL
SELECT 'TXT_KEY_CIV5_GWYNEDD_TEXT', 'Gwynedd was an independent Welsh kingdom from the end of the Roman period until the 13th century, when it was conquered by England.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MUISCA', 'Muisca' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MUISCA_ADJ', 'Muiscan' UNION ALL
SELECT 'TXT_KEY_CIV5_MUISCA_TEXT', 'Muisca was home to several Andean cultures such as the Panche in the west, Muzo in the northwest, Guane in the north, Lache in the northeast, Achagua in the east, and Sutagao in the south until the 16th century where Spanish Conquistadors laid ruin to them.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_LACONIA', 'Laconia' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_LACONIA_ADJ', 'Laconians' UNION ALL
SELECT 'TXT_KEY_CIV5_LACONIA_TEXT', 'Considered a region of its city-state capital, Sparta, Laconia became one of the strongest local powers to contest control in the Peloponnese region.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_CHEVAK', 'Chevak' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_CHEVAK_ADJ', 'The Chevak' UNION ALL
SELECT 'TXT_KEY_CIV5_CHEVAK_TEXT', 'An area in Alaska native to the Chevak people.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SANTO_DOMINGO', 'Santo Domingo' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_SANTO_DOMINGO_ADJ', 'Dominican' UNION ALL
SELECT 'TXT_KEY_CIV5_SANTO_DOMINGO_TEXT', 'Santo Domingo became the oldest European city in the Americas continent. Originally named La Nueva Isabela, it was renamed in 1495 to ''Santo Domingo'', in honor of Saint Dominic. Santo Domingo came to be known as the ''Gateway to the Caribbean'' as the city grew bigger and prosperous.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MANAGUA', 'Managua' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_MANAGUA_ADJ', 'Managuense' UNION ALL
SELECT 'TXT_KEY_CIV5_MANAGUA_TEXT', 'Managua composed of mestizos and whites of Spanish decent, the city became from a fishing town to a thriving Spanish to now being the most well-known Central American developed city.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ODENSO', 'Odenso' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_ODENSO_ADJ', 'The Odenso' UNION ALL
SELECT 'TXT_KEY_CIV5_ODENSO_TEXT', 'Translated literally as Odin''s Island, it was named by the Finnish Kingdom in recognition to a Norse Mythologial God, Odin.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_YANGCHENG', 'Yangcheng' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_YANGCHENG_ADJ', 'The Yangcheng' UNION ALL
SELECT 'TXT_KEY_CIV5_YANGCHENG_TEXT', 'Considered the first capital of the Xia Dynasty, it was built upon the Yin River and held until the fall of their dynasty.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_PHANOTEUS', 'Phanoteus' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_PHANOTEUS_ADJ', 'Phocisan' UNION ALL
SELECT 'TXT_KEY_CIV5_PHANOTEUS_TEXT', 'Phanoteus was a very ancient town, originally inhabited by the Phlegyae. It is believed that Promethesus made the human race here. It held until damaged and damaged until destroyed in the passage of time by the Persians under Xerxes, Macedonians under Philip II, and the Romans under Pompey the Great.' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DOUALA', 'Douala' UNION ALL
SELECT 'TXT_KEY_CITYSTATE_DOUALA_ADJ', 'The Douala' UNION ALL
SELECT 'TXT_KEY_CIV5_DOUALA_TEXT', 'Douala is the largest city in Cameroon along as its city with the strongest economic growth in the region. Cameroon independence in 1960 gave rise to the strong rapid economic growth of Douala as its economic importance became critical to develop and prosper.' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_GWYNEDD', '[COLOR:224:255:61:255]Cyfraith Hywel[ENDCOLOR]: +10% [ICON_CULTURE] Culture during Golden Ages.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MUISCA', '[COLOR:224:255:61:255]The Golden One[ENDCOLOR]: +1 [ICON_GOLD] Gold per 2 Citizens in the Capital and +1 [ICON_GOLD] Gold for every 30 citizens in your Empire.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_LACONIA', '[COLOR:224:255:61:255]Spartan Discipline[ENDCOLOR]: +10% [ICON_STRENGTH] Combat Strength when adjacent to a friendly unit.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_CHEVAK', '[COLOR:224:255:61:255]Cev''aq[ENDCOLOR]: +1 [ICON_FOOD] Food for every 4 Tundra Tiles or 3 Snow Tiles within workable radius.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_SANTO_DOMINGO', '[COLOR:224:255:61:255]Caribbean''s Gateway[ENDCOLOR]: +3 to the sum of Yields and Happiness from Global Monopolies.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_MANAGUA', '[COLOR:224:255:61:255]Place of the Big Man[ENDCOLOR]: +7% to the sum of Yields and Golden Age duration modifiers from Global Monopolies.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_ODENSO', '[COLOR:224:255:61:255]Lord of the Hunt[ENDCOLOR]: Military Units gain +1 Vision and heal an additional 5 HP per turn in neutral territories.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_YANGCHENG', '[COLOR:224:255:61:255]Year of the Animal[ENDCOLOR]: +1 [ICON_PEACE] Faith on Animal Resources.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_PHANOTEUS', '[COLOR:224:255:61:255]Gift of Promethesus[ENDCOLOR]: Chance of rigged elections and coups in City-States increased by +25%.  Spies +25% more likely to capture enemy spies in owned cities. Spies steal Technologies and Great Works +25% faster.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_CSTRAIT_MINOR_CIV_DOUALA', '[COLOR:224:255:61:255]Minature Continent[ENDCOLOR]: +1 [ICON_INTERNATIONAL_TRADE] Trade Route.[NEWLINE]' UNION ALL
SELECT 'TXT_KEY_BUILDING_CHEVAK', 'Cev''aq' UNION ALL
SELECT 'TXT_KEY_BUILDING_CHEVAK_HELP', '+1 [ICON_FOOD] Food for every 4 Tundra Tiles or 3 Snow Tiles.';

INSERT INTO MinorCivilizations (Type, ShortDescription, Civilopedia, Description, Adjective, ArtDefineTag, DefaultPlayerColor, ArtStyleType, ArtStyleSuffix, ArtStylePrefix, MinorCivTrait)
SELECT 'MINOR_CIV_GWYNEDD', 'TXT_KEY_CITYSTATE_GWYNEDD', 'TXT_KEY_CIV5_GWYNEDD_TEXT', 'TXT_KEY_CITYSTATE_GWYNEDD', 'TXT_KEY_CITYSTATE_GWYNEDD_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_PURPLE', 'ARTSTYLE_EUROPEAN', '_EURO', 'EUROPEAN', 'MINOR_TRAIT_CULTURED' UNION ALL
SELECT 'MINOR_CIV_MUISCA', 'TXT_KEY_CITYSTATE_MUISCA', 'TXT_KEY_CIV5_MUISCA_TEXT', 'TXT_KEY_CITYSTATE_MUISCA', 'TXT_KEY_CITYSTATE_MUISCA_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_YELLOW', 'ARTSTYLE_SOUTH_AMERICA', '_AMER', 'AMERICAN', 'MINOR_TRAIT_MERCANTILE' UNION ALL
SELECT 'MINOR_CIV_LACONIA', 'TXT_KEY_CITYSTATE_LACONIA', 'TXT_KEY_CIV5_LACONIA_TEXT', 'TXT_KEY_CITYSTATE_LACONIA', 'TXT_KEY_CITYSTATE_LACONIA_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_CYAN', 'ARTSTYLE_GRECO_ROMAN', '_MED', 'MEDITERRANEAN', 'MINOR_TRAIT_MILITARISTIC' UNION ALL
SELECT 'MINOR_CIV_CHEVAK', 'TXT_KEY_CITYSTATE_CHEVAK', 'TXT_KEY_CIV5_CHEVAK_TEXT', 'TXT_KEY_CITYSTATE_CHEVAK', 'TXT_KEY_CITYSTATE_CHEVAK_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_GREEN', 'ARTSTYLE_SOUTH_AMERICA', '_AMER', 'AMERICAN', 'MINOR_TRAIT_MARITIME' UNION ALL
SELECT 'MINOR_CIV_SANTO_DOMINGO', 'TXT_KEY_CITYSTATE_SANTO_DOMINGO', 'TXT_KEY_CIV5_SANTO_DOMINGO_TEXT', 'TXT_KEY_CITYSTATE_SANTO_DOMINGO', 'TXT_KEY_CITYSTATE_SANTO_DOMINGO_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_YELLOW', 'ARTSTYLE_EUROPEAN', '_EURO', 'EUROPEAN', 'MINOR_TRAIT_MERCANTILE' UNION ALL
SELECT 'MINOR_CIV_MANAGUA', 'TXT_KEY_CITYSTATE_MANAGUA', 'TXT_KEY_CIV5_MANAGUA_TEXT', 'TXT_KEY_CITYSTATE_MANAGUA', 'TXT_KEY_CITYSTATE_MANAGUA_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_YELLOW', 'ARTSTYLE_EUROPEAN', '_EURO', 'EUROPEAN', 'MINOR_TRAIT_MERCANTILE' UNION ALL
SELECT 'MINOR_CIV_ODENSO', 'TXT_KEY_CITYSTATE_ODENSO', 'TXT_KEY_CIV5_ODENSO_TEXT', 'TXT_KEY_CITYSTATE_ODENSO', 'TXT_KEY_CITYSTATE_ODENSO_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_CYAN', 'ARTSTYLE_EUROPEAN', '_EURO', 'EUROPEAN', 'MINOR_TRAIT_MILITARISTIC' UNION ALL
SELECT 'MINOR_CIV_YANGCHENG', 'TXT_KEY_CITYSTATE_YANGCHENG', 'TXT_KEY_CIV5_YANGCHENG_TEXT', 'TXT_KEY_CITYSTATE_YANGCHENG', 'TXT_KEY_CITYSTATE_YANGCHENG_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_WHITE', 'ARTSTYLE_ASIAN', '_ASIA', 'ASIAN', 'MINOR_TRAIT_RELIGIOUS' UNION ALL
SELECT 'MINOR_CIV_PHANOTEUS', 'TXT_KEY_CITYSTATE_PHANOTEUS', 'TXT_KEY_CIV5_PHANOTEUS_TEXT', 'TXT_KEY_CITYSTATE_PHANOTEUS', 'TXT_KEY_CITYSTATE_PHANOTEUS_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_YELLOW', 'ARTSTYLE_GRECO_ROMAN', '_MED', 'MEDITERRANEAN', 'MINOR_TRAIT_MILITARISTIC' UNION ALL
SELECT 'MINOR_CIV_DOUALA', 'TXT_KEY_CITYSTATE_DOUALA', 'TXT_KEY_CIV5_DOUALA_TEXT', 'TXT_KEY_CITYSTATE_DOUALA', 'TXT_KEY_CITYSTATE_DOUALA_ADJ', 'ART_DEF_CIVILIZATION_MINOR', 'PLAYERCOLOR_MINOR_YELLOW', 'ARTSTYLE_MIDDLE_EAST', '_AFRI', 'AFRICAN', 'MINOR_TRAIT_MERCANTILE';

INSERT INTO MinorCivilization_CityNames (MinorCivType, CityName)
SELECT 'MINOR_CIV_GWYNEDD', 'TXT_KEY_CITYSTATE_GWYNEDD' UNION ALL
SELECT 'MINOR_CIV_MUISCA', 'TXT_KEY_CITYSTATE_MUISCA' UNION ALL
SELECT 'MINOR_CIV_LACONIA', 'TXT_KEY_CITYSTATE_LACONIA' UNION ALL
SELECT 'MINOR_CIV_CHEVAK', 'TXT_KEY_CITYSTATE_CHEVAK' UNION ALL
SELECT 'MINOR_CIV_SANTO_DOMINGO', 'TXT_KEY_CITYSTATE_SANTO_DOMINGO' UNION ALL
SELECT 'MINOR_CIV_MANAGUA', 'TXT_KEY_CITYSTATE_MANAGUA' UNION ALL
SELECT 'MINOR_CIV_ODENSO', 'TXT_KEY_CITYSTATE_ODENSO' UNION ALL
SELECT 'MINOR_CIV_YANGCHENG', 'TXT_KEY_CITYSTATE_YANGCHENG' UNION ALL
SELECT 'MINOR_CIV_PHANOTEUS', 'TXT_KEY_CITYSTATE_PHANOTEUS' UNION ALL
SELECT 'MINOR_CIV_DOUALA', 'TXT_KEY_CITYSTATE_DOUALA';

INSERT INTO MinorCivilization_Flavors (MinorCivType, FlavorType, Flavor)
SELECT 'MINOR_CIV_GWYNEDD', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_GWYNEDD', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_GWYNEDD', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_GWYNEDD', 'FLAVOR_CULTURE', 10 UNION ALL
SELECT 'MINOR_CIV_MUISCA', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_MUISCA', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_MUISCA', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_MUISCA', 'FLAVOR_GOLD', 10 UNION ALL
SELECT 'MINOR_CIV_LACONIA', 'FLAVOR_OFFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_LACONIA', 'FLAVOR_DEFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_LACONIA', 'FLAVOR_MILITARY_TRAINING', 7 UNION ALL
SELECT 'MINOR_CIV_LACONIA', 'FLAVOR_CITY_DEFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_LACONIA', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_LACONIA', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_LACONIA', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_CHEVAK', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_CHEVAK', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_CHEVAK', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_CHEVAK', 'FLAVOR_GROWTH', 8 UNION ALL
SELECT 'MINOR_CIV_CHEVAK', 'FLAVOR_NAVAL', 8 UNION ALL
SELECT 'MINOR_CIV_SANTO_DOMINGO', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_SANTO_DOMINGO', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_SANTO_DOMINGO', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_SANTO_DOMINGO', 'FLAVOR_GOLD', 10 UNION ALL
SELECT 'MINOR_CIV_MANAGUA', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_MANAGUA', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_MANAGUA', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_MANAGUA', 'FLAVOR_GOLD', 10 UNION ALL
SELECT 'MINOR_CIV_ODENSO', 'FLAVOR_OFFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_ODENSO', 'FLAVOR_DEFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_ODENSO', 'FLAVOR_MILITARY_TRAINING', 7 UNION ALL
SELECT 'MINOR_CIV_ODENSO', 'FLAVOR_CITY_DEFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_ODENSO', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_ODENSO', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_ODENSO', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_YANGCHENG', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_YANGCHENG', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_YANGCHENG', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_YANGCHENG', 'FLAVOR_RELIGION', 10 UNION ALL
SELECT 'MINOR_CIV_PHANOTEUS', 'FLAVOR_OFFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_PHANOTEUS', 'FLAVOR_DEFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_PHANOTEUS', 'FLAVOR_MILITARY_TRAINING', 7 UNION ALL
SELECT 'MINOR_CIV_PHANOTEUS', 'FLAVOR_CITY_DEFENSE', 7 UNION ALL
SELECT 'MINOR_CIV_PHANOTEUS', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_PHANOTEUS', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_PHANOTEUS', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_DOUALA', 'FLAVOR_EXPANSION', 0 UNION ALL
SELECT 'MINOR_CIV_DOUALA', 'FLAVOR_NUKE', 0 UNION ALL
SELECT 'MINOR_CIV_DOUALA', 'FLAVOR_WONDER', 0 UNION ALL
SELECT 'MINOR_CIV_DOUALA', 'FLAVOR_GOLD', 10;

INSERT INTO UnitPromotions (Type, Description, Help, CannotBeChosen, Sound, PortraitIndex, IconAtlas, PediaType, PediaEntry)
SELECT 'PROMOTION_LACONIA', 'TXT_KEY_CITYSTATE_LACONIA', 'TXT_KEY_CSTRAIT_MINOR_CIV_LACONIA', 1, 'AS2D_IF_LEVELUP', 10, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CITYSTATE_LACONIA_HELP1' UNION ALL
SELECT 'PROMOTION_ODENSO', 'TXT_KEY_CITYSTATE_ODENSO', 'TXT_KEY_CSTRAIT_MINOR_CIV_ODENSO', 1, 'AS2D_IF_LEVELUP', 12, 'UCS2_ATLAS', 'PEDIA_ATTRIBUTES', 'TXT_KEY_CITYSTATE_ODENSO_HELP1';

UPDATE UnitPromotions
SET AdjacentMod = 10
WHERE Type = 'PROMOTION_LACONIA';

UPDATE UnitPromotions
SET NeutralHealChange = 5, VisibilityChange = 1
WHERE Type = 'PROMOTION_ODENSO';

INSERT INTO UnitPromotions_UnitCombats (PromotionType, UnitCombatType)
SELECT 'PROMOTION_LACONIA', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_LACONIA', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_LACONIA', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_LACONIA', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_LACONIA', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_LACONIA', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_LACONIA', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_LACONIA', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_LACONIA', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_LACONIA', 'UNITCOMBAT_NAVALRANGED' UNION ALL
SELECT 'PROMOTION_ODENSO', 'UNITCOMBAT_RECON' UNION ALL
SELECT 'PROMOTION_ODENSO', 'UNITCOMBAT_ARCHER' UNION ALL
SELECT 'PROMOTION_ODENSO', 'UNITCOMBAT_MOUNTED' UNION ALL
SELECT 'PROMOTION_ODENSO', 'UNITCOMBAT_MELEE' UNION ALL
SELECT 'PROMOTION_ODENSO', 'UNITCOMBAT_SIEGE' UNION ALL
SELECT 'PROMOTION_ODENSO', 'UNITCOMBAT_GUN' UNION ALL
SELECT 'PROMOTION_ODENSO', 'UNITCOMBAT_ARMOR' UNION ALL
SELECT 'PROMOTION_ODENSO', 'UNITCOMBAT_HELICOPTER' UNION ALL
SELECT 'PROMOTION_ODENSO', 'UNITCOMBAT_NAVALMELEE' UNION ALL
SELECT 'PROMOTION_ODENSO', 'UNITCOMBAT_NAVALRANGED';

INSERT INTO BuildingClasses (Type, DefaultBuilding, Description)
SELECT 'BUILDINGCLASS_CHEVAK', 'BUILDING_CHEVAK', 'TXT_KEY_BUILDING_CHEVAK';

INSERT INTO Buildings (Type, BuildingClass, Cost, GoldMaintenance, PrereqTech, Description, Help, MinAreaSize, NukeImmune, ConquestProb, NeverCapture, HurryCostModifier, IconAtlas, PortraitIndex, IsDummy)
SELECT 'BUILDING_CHEVAK', 'BUILDINGCLASS_CHEVAK', -1, 0, NULL, 'TXT_KEY_BUILDING_CHEVAK', 'TXT_KEY_BUILDING_CHEVAK_HELP', -1, 1, 0, 1, 5, 'UCS_ATLAS', 1, 1;

INSERT INTO Building_YieldPerXTerrainTimes100 (BuildingType, TerrainType, YieldType, Yield)
SELECT 'BUILDING_CHEVAK', 'TERRAIN_TUNDRA', 'YIELD_FOOD', 25 UNION ALL
SELECT 'BUILDING_CHEVAK', 'TERRAIN_SNOW', 'YIELD_FOOD', 33;

INSERT INTO Policies (Type, Description)
SELECT 'POLICY_GWYNEDD', 'TXT_KEY_CITYSTATE_GWYNEDD' UNION ALL
SELECT 'POLICY_MUISCA', 'TXT_KEY_CITYSTATE_MUISCA' UNION ALL
SELECT 'POLICY_SANTO_DOMINGO', 'TXT_KEY_CITYSTATE_SANTO_DOMINGO' UNION ALL
SELECT 'POLICY_MANAGUA', 'TXT_KEY_CITYSTATE_MANAGUA' UNION ALL
SELECT 'POLICY_PHANOTEUS', 'TXT_KEY_CITYSTATE_PHANOTEUS' UNION ALL
SELECT 'POLICY_DOUALA', 'TXT_KEY_CITYSTATE_DOUALA';

INSERT INTO Policy_GoldenAgeYieldMod(PolicyType, YieldType, Yield)
SELECT 'POLICY_GWYNEDD', 'YIELD_CULTURE', 10;

INSERT INTO Policy_CapitalYieldPerPopChanges(PolicyType, YieldType, Yield)
SELECT 'POLICY_MUISCA', 'YIELD_GOLD', 50;

INSERT INTO Policy_CapitalYieldPerPopChangeEmpire(PolicyType, YieldType, Yield)
SELECT 'POLICY_MUISCA', 'YIELD_GOLD', 30;

UPDATE Policies
SET MonopolyModFlat = 3
WHERE Type = 'POLICY_SANTO_DOMINGO';

UPDATE Policies
SET MonopolyModPercent = 7
WHERE Type = 'POLICY_MANAGUA';

UPDATE Policies
SET StealGWFasterModifier = 25, StealTechFasterModifier = 25, RiggingElectionModifier = 25, CatchSpiesModifier = 25
WHERE Type = 'POLICY_PHANOTEUS';

UPDATE Policies
SET FreeTradeRoute = 1
WHERE Type = 'POLICY_DOUALA';

INSERT INTO Events (Type, Description, Help, EventArt, RandomChance, NumChoices, IgnoresGlobalCooldown, EventCooldown)
SELECT  'PLAYER_EVENT_MINOR_CIV_GWYNEDD', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_GWYNEDD', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_MUISCA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MUISCA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_LACONIA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_LACONIA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_CHEVAK', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_CHEVAK', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_SANTO_DOMINGO', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_SANTO_DOMINGO', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_MANAGUA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MANAGUA', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_ODENSO', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ODENSO', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_YANGCHENG', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_YANGCHENG', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_PHANOTEUS', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_PHANOTEUS', 'AllianceShift.dds', -1, 1, 1, 1 UNION ALL
SELECT  'PLAYER_EVENT_MINOR_CIV_DOUALA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_DOUALA', 'AllianceShift.dds', -1, 1, 1, 1;

INSERT INTO EventChoices (Type, Description, Help, EventDuration, Expires, EventPolicy, EventPromotion, EventBuildingClassGlobal)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_GWYNEDD', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_GWYNEDD', 3, 1, 'POLICY_GWYNEDD', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MUISCA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MUISCA', 3, 1, 'POLICY_MUISCA', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LACONIA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_LACONIA', 3, 1, NULL, 'PROMOTION_LACONIA', NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_CHEVAK', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_CHEVAK', 3, 1, NULL, NULL, 'BUILDINGCLASS_CHEVAK' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_SANTO_DOMINGO', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_SANTO_DOMINGO', 3, 1, 'POLICY_SANTO_DOMINGO', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MANAGUA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_MANAGUA', 3, 1, 'POLICY_MANAGUA', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ODENSO', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_ODENSO', 3, 1, NULL, 'PROMOTION_ODENSO', NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_YANGCHENG', 3, 1, NULL, NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_PHANOTEUS', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_PHANOTEUS', 3, 1, 'POLICY_PHANOTEUS', NULL, NULL UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_DOUALA', 'TXT_KEY_CSTRAIT_MINOR_CIV', 'TXT_KEY_CSTRAIT_MINOR_CIV_DOUALA', 3, 1, 'POLICY_DOUALA', NULL, NULL;

INSERT INTO Event_ParentEvents (EventChoiceType, EventType)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_GWYNEDD', 'PLAYER_EVENT_MINOR_CIV_GWYNEDD' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MUISCA', 'PLAYER_EVENT_MINOR_CIV_MUISCA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_LACONIA', 'PLAYER_EVENT_MINOR_CIV_LACONIA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_CHEVAK', 'PLAYER_EVENT_MINOR_CIV_CHEVAK' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_SANTO_DOMINGO', 'PLAYER_EVENT_MINOR_CIV_SANTO_DOMINGO' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_MANAGUA', 'PLAYER_EVENT_MINOR_CIV_MANAGUA' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_ODENSO', 'PLAYER_EVENT_MINOR_CIV_ODENSO' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'PLAYER_EVENT_MINOR_CIV_YANGCHENG' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_PHANOTEUS', 'PLAYER_EVENT_MINOR_CIV_PHANOTEUS' UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_DOUALA', 'PLAYER_EVENT_MINOR_CIV_DOUALA';

INSERT INTO EventChoice_ResourceYieldChange (EventChoiceType, ResourceType, YieldType, YieldChange)
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'RESOURCE_COW', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'RESOURCE_SHEEP', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'RESOURCE_DEER', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'RESOURCE_FISH', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'RESOURCE_BISON', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'RESOURCE_WHALE', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'RESOURCE_PEARLS', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'RESOURCE_IVORY', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'RESOURCE_FUR', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'RESOURCE_CRAB', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'RESOURCE_TRUFFLES', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'RESOURCE_CORAL', 'YIELD_FAITH', 1 UNION ALL
SELECT 'PLAYER_EVENT_CHOICE_MINOR_CIV_YANGCHENG', 'RESOURCE_HORSE', 'YIELD_FAITH', 1;

UPDATE Defines
SET Value = '5'
WHERE Name = 'ALLIES_SCIENCE_FLAT_BONUS_AMOUNT_INDUSTRIAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '6'
WHERE Name = 'ALLIES_SCIENCE_FLAT_BONUS_AMOUNT_RENAISSANCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '5'
WHERE Name = 'ALLIES_SCIENCE_FLAT_BONUS_AMOUNT_MEDIEVAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '4'
WHERE Name = 'ALLIES_SCIENCE_FLAT_BONUS_AMOUNT_CLASSICAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '2'
WHERE Name = 'ALLIES_SCIENCE_FLAT_BONUS_AMOUNT_ANCIENT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '4'
WHERE Name = 'ALLIES_GOLD_FLAT_BONUS_AMOUNT_INDUSTRIAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '3'
WHERE Name = 'ALLIES_GOLD_FLAT_BONUS_AMOUNT_RENAISSANCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '3'
WHERE Name = 'ALLIES_GOLD_FLAT_BONUS_AMOUNT_MEDIEVAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '2'
WHERE Name = 'ALLIES_GOLD_FLAT_BONUS_AMOUNT_CLASSICAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '1'
WHERE Name = 'ALLIES_GOLD_FLAT_BONUS_AMOUNT_ANCIENT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '7'
WHERE Name = 'ALLIES_CULTURE_BONUS_AMOUNT_INDUSTRIAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '4'
WHERE Name = 'ALLIES_CULTURE_BONUS_AMOUNT_MEDIEVAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '2'
WHERE Name = 'ALLIES_CULTURE_BONUS_AMOUNT_ANCIENT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '9'
WHERE Name = 'ALLIES_FAITH_FLAT_BONUS_AMOUNT_INDUSTRIAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '8'
WHERE Name = 'ALLIES_FAITH_FLAT_BONUS_AMOUNT_RENAISSANCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '6'
WHERE Name = 'ALLIES_FAITH_FLAT_BONUS_AMOUNT_MEDIEVAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '4'
WHERE Name = 'ALLIES_FAITH_FLAT_BONUS_AMOUNT_CLASSICAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '2'
WHERE Name = 'ALLIES_FAITH_FLAT_BONUS_AMOUNT_ANCIENT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '100'
WHERE Name = 'ALLIES_CAPITAL_FOOD_BONUS_AMOUNT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );

UPDATE Defines
SET Value = '100'
WHERE Name = 'ALLIES_OTHER_CITIES_FOOD_BONUS_AMOUNT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MINORS' AND Value= 1 );